using System.Text.Json.Serialization;

namespace ZoomNet.Models
{
	/// <summary>
	/// Information about phone call party, i.e. caller or callee.
	/// </summary>
	public class PhoneCallParty
	{
		/// <summary>
		/// Gets or sets the phone number in E.164 format.
		/// </summary>
		[JsonPropertyName("phone_number")]
		public string PhoneNumber { get; set;  }

		/// <summary>
		/// Gets or sets the account code.
		/// </summary>
		[JsonPropertyName("account_name")]
		public string AccountCode { get; set;  }

		/// <summary>
		/// Gets or sets connection type.
		/// </summary>
		[JsonPropertyName("connection_type")]
		public PhoneCallConnectionType? ConnectionType { get; set; }

		/// <summary>
		/// Gets or sets id generated by Zoom client when installed on a device.
		/// </summary>
		[JsonPropertyName("device_id")]
		public string DeviceId { get; set; }

		/// <summary>
		/// Gets or sets the name of the device on which Zoom client is installed.
		/// </summary>
		[JsonPropertyName("device_name")]
		public string DeviceName { get; set; }

		/// <summary>
		/// Gets or sets the type of device on which Zoom client is installed.
		/// </summary>
		[JsonPropertyName("device_type")]
		public string DeviceType { get; set; }

		/// <summary>
		/// Gets or sets the extension id.
		/// </summary>
		[JsonPropertyName("extension_id")]
		public string ExtensionId { get; set; }

		/// <summary>
		/// Gets or sets the extension number.
		/// </summary>
		[JsonPropertyName("extension_number")]
		[JsonNumberHandling(JsonNumberHandling.AllowReadingFromString)]
		public long? ExtensionNumber { get; set; }

		/// <summary>
		/// Gets or sets the extension type.
		/// </summary>
		[JsonPropertyName("extension_type")]
		public PhoneCallExtensionType? ExtensionType { get; set; }

		/// <summary>
		/// Gets or sets the user name.
		/// </summary>
		[JsonPropertyName("name")]
		public string Name { get; set; }

		/// <summary>
		/// Gets or sets the timezone.
		/// </summary>
		[JsonPropertyName("timezone")]
		public TimeZones? Timezone { get; set; }

		/// <summary>
		/// Gets or sets Zoom user id.
		/// </summary>
		[JsonPropertyName("user_id")]
		public string UserId { get; set; }
	}
}
