using System;
using System.Collections.Generic;
using ZoomNet.Models;

namespace ZoomNet
{
	/// <summary>
	/// The delegate invoked when a token is refreshed.
	/// </summary>
	/// <param name="newRefreshToken">The new refresh token.</param>
	/// <param name="newAccessToken">The new access token.</param>
	public delegate void OnTokenRefreshedDelegate(string newRefreshToken, string newAccessToken);

	/// <summary>
	/// Connect using OAuth.
	/// </summary>
	public class OAuthConnectionInfo : IConnectionInfo
	{
		/// <summary>
		/// Gets the client id.
		/// </summary>
		public string ClientId { get; }

		/// <summary>
		/// Gets the client secret.
		/// </summary>
		public string ClientSecret { get; }

		/// <summary>
		/// Gets the grant type.
		/// </summary>
		public OAuthGrantType GrantType { get; internal set; }

		/// <summary>
		/// Gets the authorization code.
		/// </summary>
		public string AuthorizationCode { get; }

		/// <summary>
		/// Gets the refresh token.
		/// </summary>
		public string RefreshToken { get; internal set; }

		/// <summary>
		/// Gets the access token.
		/// </summary>
		public string AccessToken { get; internal set; }

		/// <summary>
		/// Gets the token scope.
		/// </summary>
		public IReadOnlyDictionary<string, string[]> TokenScope { get; internal set; }

		/// <summary>
		/// Gets the token expiration time.
		/// </summary>
		public DateTime TokenExpiration { get; internal set; }

		/// <summary>
		/// Gets the delegate invoked when the token is refreshed.
		/// </summary>
		public OnTokenRefreshedDelegate OnTokenRefreshed { get; }

		/// <summary>
		/// Gets the redirectUri required for refresh of tokens.
		/// </summary>
		public string RedirectUri { get; }

		/// <summary>
		/// Initializes a new instance of the <see cref="OAuthConnectionInfo"/> class.
		/// </summary>
		/// <remarks>
		/// This constructor is used to get access token for APIs that do not
		/// need a user's permission, but rather a service's permission.
		/// Within the realm of Zoom APIs, Client Credentials grant should be
		/// used to get access token from the Chatbot Service in order to use
		/// the "Send Chatbot Messages API". See the "Using OAuth 2.0 / Client
		/// Credentials" section in the "Using Zoom APIs" document for more details
		/// (https://marketplace.zoom.us/docs/api-reference/using-zoom-apis).
		/// </remarks>
		/// <param name="clientId">Your Client Id.</param>
		/// <param name="clientSecret">Your Client Secret.</param>
		public OAuthConnectionInfo(string clientId, string clientSecret)
		{
			ClientId = clientId ?? throw new ArgumentNullException(nameof(clientId));
			ClientSecret = clientSecret ?? throw new ArgumentNullException(nameof(clientSecret));
			GrantType = OAuthGrantType.ClientCredentials;
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="OAuthConnectionInfo"/> class.
		/// </summary>
		/// <remarks>
		/// The authorization code is generated by Zoom when the user authorizes the app.
		/// This code can be used only one time to get the initial access token and refresh token.
		/// Once the authorization code has been used, is is no longer valid and should be discarded.
		///
		/// Also, Zoom's documentation says that the redirect uri must be provided when validating an
		/// authorization code and converting it into tokens. However I have observed that it's not
		/// always necessary. It seems that some developers get a "REDIRECT URI MISMATCH" exception when
		/// they omit this value but other developers don't. Therefore, the redirectUri parameter is
		/// marked as optional in ZoomNet which allows you to specify it or omit it depending on your
		/// situation. See this <a href="">Github issue</a> for more details.
		/// </remarks>
		/// <param name="clientId">Your Client Id.</param>
		/// <param name="clientSecret">Your Client Secret.</param>
		/// <param name="authorizationCode">The authorization code.</param>
		/// <param name="onTokenRefreshed">The delegate invoked when the token is refreshed.</param>
		/// <param name="redirectUri">The Redirect Uri.</param>
		public OAuthConnectionInfo(string clientId, string clientSecret, string authorizationCode, OnTokenRefreshedDelegate onTokenRefreshed, string redirectUri = null)
		{
			ClientId = clientId ?? throw new ArgumentNullException(nameof(clientId));
			ClientSecret = clientSecret ?? throw new ArgumentNullException(nameof(clientSecret));
			AuthorizationCode = authorizationCode ?? throw new ArgumentNullException(nameof(authorizationCode));
			RedirectUri = redirectUri;
			TokenExpiration = DateTime.MinValue;
			GrantType = OAuthGrantType.AuthorizationCode;
			OnTokenRefreshed = onTokenRefreshed;
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="OAuthConnectionInfo"/> class.
		/// </summary>
		/// <remarks>
		/// This is the most commonly used grant type for Zoom APIs.
		/// </remarks>
		/// <param name="clientId">Your Client Id.</param>
		/// <param name="clientSecret">Your Client Secret.</param>
		/// <param name="refreshToken">The refresh token.</param>
		/// <param name="accessToken">The access token. Access tokens expire after 1 hour. ZoomNet will automatically refresh this token when it expires.</param>
		/// <param name="onTokenRefreshed">The delegate invoked when the token is refreshed.</param>
		public OAuthConnectionInfo(string clientId, string clientSecret, string refreshToken, string accessToken, OnTokenRefreshedDelegate onTokenRefreshed)
		{
			ClientId = clientId ?? throw new ArgumentNullException(nameof(clientId));
			ClientSecret = clientSecret ?? throw new ArgumentNullException(nameof(clientSecret));
			RefreshToken = refreshToken ?? throw new ArgumentNullException(nameof(refreshToken));
			AccessToken = accessToken ?? throw new ArgumentNullException(nameof(accessToken));
			TokenExpiration = string.IsNullOrEmpty(accessToken) ? DateTime.MinValue : DateTime.MaxValue; // Set expiration to DateTime.MaxValue when an access token is provided because we don't know when it will expire
			GrantType = OAuthGrantType.RefreshToken;
			OnTokenRefreshed = onTokenRefreshed;
		}
	}
}
