//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZoomNet.UnitTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EndpointsResponseResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EndpointsResponseResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZoomNet.UnitTests.Properties.EndpointsResponseResource", typeof(EndpointsResponseResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;from&quot;: &quot;2021-03-12T02:12:27.0000000\u002B00:00&quot;,
        ///  &quot;meetings&quot;: [
        ///    {
        ///      &quot;account_name&quot;: &quot;account_01&quot;,
        ///      &quot;archive_files&quot;: [
        ///        {
        ///          &quot;download_url&quot;: &quot;https://example.com/recording/download/Qg75t7xZBtEbAkjdlgbfdngBBBB&quot;,
        ///          &quot;file_extension&quot;: &quot;JSON&quot;,
        ///          &quot;file_path&quot;: &quot;/9090876528/path01/demo.mp4&quot;,
        ///          &quot;file_size&quot;: 165743,
        ///          &quot;file_type&quot;: &quot;CHAT&quot;,
        ///          &quot;id&quot;: &quot;a2f19f96-9294-4f51-8134-6f0eea108eb2&quot;,
        ///          &quot;individual&quot;: true,
        ///          &quot;partic [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string archive_files_GET {
            get {
                return ResourceManager.GetString("archive_files_GET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;from&quot;: &quot;2021-03-18T05:41:36.0000000\u002B00:00&quot;,
        ///  &quot;to&quot;: &quot;2021-03-18T05:41:36.0000000\u002B00:00&quot;,
        ///  &quot;total_records&quot;: 20,
        ///  &quot;statistic_by_file_extension&quot;: {
        ///    &quot;mp4_file_count&quot;: 1,
        ///    &quot;m4a_file_count&quot;: 1,
        ///    &quot;txt_file_count&quot;: 1,
        ///    &quot;json_file_count&quot;: 1,
        ///    &quot;vtt_file_count&quot;: 1
        ///  },
        ///  &quot;statistic_by_file_status&quot;: {
        ///    &quot;processing_file_count&quot;: 1,
        ///    &quot;completed_file_count&quot;: 1,
        ///    &quot;failed_file_count&quot;: 1
        ///  }
        ///}.
        /// </summary>
        internal static string archive_files_statistics_GET {
            get {
                return ResourceManager.GetString("archive_files-statistics_GET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;next_page_token&quot;: &quot;At6eWnFZ1FB3arCXnRxqHLXKhbDW18yz2i2&quot;,
        ///  &quot;page_size&quot;: 20,
        ///  &quot;devices&quot;: [
        ///    {
        ///      &quot;device_id&quot;: &quot;F1C6E9DF-429E-4FA1-85DA-AC95464F3D18&quot;,
        ///      &quot;device_name&quot;: &quot;My device&quot;,
        ///      &quot;mac_address&quot;: &quot;01-23-45-67-89-AB&quot;,
        ///      &quot;serial_number&quot;: &quot;6NRN2A0&quot;,
        ///      &quot;vendor&quot;: &quot;Poly&quot;,
        ///      &quot;model&quot;: &quot;StudioX30&quot;,
        ///      &quot;platform_os&quot;: &quot;Epos expandvision5 1.2.22315.04&quot;,
        ///      &quot;app_version&quot;: &quot;5.13.0.5762&quot;,
        ///      &quot;tag&quot;: &quot;personal rooms&quot;,
        ///      &quot;enrolled_in_zdm&quot;: true,
        ///      &quot;connected_to_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string devices_GET {
            get {
                return ResourceManager.GetString("devices_GET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;expire_in&quot;: 120,
        ///  &quot;token&quot;: &quot;2njt50mj&quot;
        ///}.
        /// </summary>
        internal static string meetings__meetingId__jointoken_local_archiving_GET {
            get {
                return ResourceManager.GetString("meetings-{meetingId}-jointoken-local_archiving_GET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;from&quot;: &quot;Microsoft.OpenApi.Any.OpenApiDate&quot;,
        ///  &quot;to&quot;: &quot;Microsoft.OpenApi.Any.OpenApiDate&quot;,
        ///  &quot;next_page_token&quot;: &quot;R4aF9Oj0fVM2hhezJTEmSKaBSkfesDwGy42&quot;,
        ///  &quot;page_size&quot;: 30,
        ///  &quot;total_records&quot;: 5,
        ///  &quot;analytics_details&quot;: [
        ///    {
        ///      &quot;date_time&quot;: &quot;2021-07-04T22:14:57.0000000\u002B00:00&quot;,
        ///      &quot;name&quot;: &quot;2&quot;,
        ///      &quot;email&quot;: &quot;2&quot;,
        ///      &quot;duration&quot;: 60
        ///    }
        ///  ]
        ///}.
        /// </summary>
        internal static string meetings__meetingId__recordings_analytics_details_GET {
            get {
                return ResourceManager.GetString("meetings-{meetingId}-recordings-analytics_details_GET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;from&quot;: &quot;Microsoft.OpenApi.Any.OpenApiDate&quot;,
        ///  &quot;to&quot;: &quot;Microsoft.OpenApi.Any.OpenApiDate&quot;,
        ///  &quot;analytics_summary&quot;: [
        ///    {
        ///      &quot;date&quot;: &quot;2022-07-06&quot;,
        ///      &quot;views_total_count&quot;: 2,
        ///      &quot;downloads_total_count&quot;: 2
        ///    }
        ///  ]
        ///}.
        /// </summary>
        internal static string meetings__meetingId__recordings_analytics_summary_GET {
            get {
                return ResourceManager.GetString("meetings-{meetingId}-recordings-analytics_summary_GET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;custom_questions&quot;: [
        ///    {
        ///      &quot;answers&quot;: [
        ///        &quot;true&quot;
        ///      ],
        ///      &quot;required&quot;: true,
        ///      &quot;title&quot;: &quot;What\u0027s your name?&quot;,
        ///      &quot;type&quot;: &quot;short&quot;
        ///    }
        ///  ],
        ///  &quot;questions&quot;: [
        ///    {
        ///      &quot;field_name&quot;: &quot;last_name&quot;,
        ///      &quot;required&quot;: true
        ///    }
        ///  ]
        ///}.
        /// </summary>
        internal static string meetings__meetingId__recordings_registrants_questions_GET {
            get {
                return ResourceManager.GetString("meetings-{meetingId}-recordings-registrants-questions_GET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;approval_type&quot;: 0,
        ///  &quot;authentication_domains&quot;: &quot;example.com&quot;,
        ///  &quot;authentication_option&quot;: &quot;auth_option&quot;,
        ///  &quot;authentication_name&quot;: &quot;auth display name&quot;,
        ///  &quot;on_demand&quot;: false,
        ///  &quot;password&quot;: &quot;975238724&quot;,
        ///  &quot;recording_authentication&quot;: true,
        ///  &quot;send_email_to_host&quot;: false,
        ///  &quot;share_recording&quot;: &quot;publicly&quot;,
        ///  &quot;show_social_share_buttons&quot;: true,
        ///  &quot;topic&quot;: &quot;My Personal Meeting Room&quot;,
        ///  &quot;viewer_download&quot;: true,
        ///  &quot;auto_delete&quot;: true,
        ///  &quot;auto_delete_date&quot;: &quot;2028-07-12&quot;
        ///}.
        /// </summary>
        internal static string meetings__meetingId__recordings_settings_GET {
            get {
                return ResourceManager.GetString("meetings-{meetingId}-recordings-settings_GET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;meeting_id&quot;: &quot;uaFkQyFCSwya8iNYtkAw3A==&quot;,
        ///  &quot;account_id&quot;: &quot;Cx3wERazSgup7ZWRHQM8-w&quot;,
        ///  &quot;meeting_topic&quot;: &quot;My Personal Meeting&quot;,
        ///  &quot;host_id&quot;: &quot;_0ctZtY0REqWalTmwvrdIw&quot;,
        ///  &quot;transcript_created_time&quot;: &quot;2025-06-27T13:48:24Z&quot;,
        ///  &quot;can_download&quot;: true,
        ///  &quot;auto_delete&quot;: true,
        ///  &quot;auto_delete_date&quot;: &quot;2052-11-07&quot;,
        ///  &quot;download_url&quot;: &quot;https://example.com/rec/meeting/transcript/download/YDztop0PYLrAQat616a1q1H86RM4jf1Bf3p42a4Ap1jV3bWAJAE.jjixtQU52SEwrsuJ&quot;,
        ///  &quot;download_restriction_reason&quot;: &quot;NOT_READY&quot;
        ///}.
        /// </summary>
        internal static string meetings__meetingId__transcript_GET {
            get {
                return ResourceManager.GetString("meetings-{meetingId}-transcript_GET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;account_name&quot;: &quot;account_01&quot;,
        ///  &quot;archive_files&quot;: [
        ///    {
        ///      &quot;download_url&quot;: &quot;https://example.com/recording/download/Qg75t7xZBtEbAkjdlgbfdngBBBB&quot;,
        ///      &quot;file_extension&quot;: &quot;JSON&quot;,
        ///      &quot;file_path&quot;: &quot;/9090876528/path01/demo.mp4&quot;,
        ///      &quot;file_size&quot;: 165743,
        ///      &quot;file_type&quot;: &quot;CHAT&quot;,
        ///      &quot;id&quot;: &quot;a2f19f96-9294-4f51-8134-6f0eea108eb2&quot;,
        ///      &quot;individual&quot;: true,
        ///      &quot;participant_email&quot;: &quot;jchill@example.com&quot;,
        ///      &quot;participant_join_time&quot;: &quot;2021-03-12T02:07:27.0000000\u002B00:00&quot;,
        ///      &quot;par [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string past_meetings__meetingUUID__archive_files_GET {
            get {
                return ResourceManager.GetString("past_meetings-{meetingUUID}-archive_files_GET", resourceCulture);
            }
        }
    }
}
