//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZoomNet.UnitTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZoomNet.UnitTests.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;event&quot;: &quot;meeting.alert&quot;,
        ///	&quot;event_ts&quot;: 1626230691572,
        ///	&quot;payload&quot;: {
        ///		&quot;account_id&quot;: &quot;AAAAAABBBB&quot;,
        ///		&quot;object&quot;: {
        ///			&quot;id&quot;: 1234567890,
        ///			&quot;uuid&quot;: &quot;4444AAAiAAAAAiAiAiiAii==&quot;,
        ///			&quot;host_id&quot;: &quot;x1yCzABCDEfg23HiJKl4mN&quot;,
        ///			&quot;topic&quot;: &quot;My Meeting&quot;,
        ///			&quot;type&quot;: 2,
        ///			&quot;start_time&quot;: &quot;2021-07-13T21:44:51Z&quot;,
        ///			&quot;timezone&quot;: &quot;America/Los_Angeles&quot;,
        ///			&quot;duration&quot;: 60,
        ///			&quot;issues&quot;: [
        ///				&quot;Unstable audio quality&quot;
        ///			]
        ///		}
        ///	}
        ///}.
        /// </summary>
        internal static string meeting_alert_webhook {
            get {
                return ResourceManager.GetString("meeting_alert_webhook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;event&quot;: &quot;meeting.breakout_room_sharing_ended&quot;,
        ///	&quot;event_ts&quot;: 1626230691572,
        ///	&quot;payload&quot;: {
        ///		&quot;account_id&quot;: &quot;AAAAAABBBB&quot;,
        ///		&quot;object&quot;: {
        ///			&quot;id&quot;: &quot;1234567890&quot;,
        ///			&quot;uuid&quot;: &quot;4444AAAiAAAAAiAiAiiAii==&quot;,
        ///			&quot;breakout_room_uuid&quot;: &quot;FkQbpP2UR028mDrwzEahqw==&quot;,
        ///			&quot;host_id&quot;: &quot;x1yCzABCDEfg23HiJKl4mN&quot;,
        ///			&quot;topic&quot;: &quot;My Meeting&quot;,
        ///			&quot;type&quot;: 8,
        ///			&quot;start_time&quot;: &quot;2021-07-13T21:44:51Z&quot;,
        ///			&quot;timezone&quot;: &quot;America/Los_Angeles&quot;,
        ///			&quot;duration&quot;: 60,
        ///			&quot;participant&quot;: {
        ///				&quot;user_id&quot;: &quot;31228928&quot;,
        ///				&quot;parent_user_i [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string meeting_breakout_room_sharing_ended_webhook {
            get {
                return ResourceManager.GetString("meeting_breakout_room_sharing_ended_webhook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;event&quot;: &quot;meeting.breakout_room_sharing_started&quot;,
        ///	&quot;event_ts&quot;: 1626230691572,
        ///	&quot;payload&quot;: {
        ///		&quot;account_id&quot;: &quot;AAAAAABBBB&quot;,
        ///		&quot;object&quot;: {
        ///			&quot;id&quot;: &quot;1234567890&quot;,
        ///			&quot;uuid&quot;: &quot;4444AAAiAAAAAiAiAiiAii==&quot;,
        ///			&quot;breakout_room_uuid&quot;: &quot;FkQbpP2UR028mDrwzEahqw==&quot;,
        ///			&quot;host_id&quot;: &quot;x1yCzABCDEfg23HiJKl4mN&quot;,
        ///			&quot;topic&quot;: &quot;My Meeting&quot;,
        ///			&quot;type&quot;: 8,
        ///			&quot;start_time&quot;: &quot;2021-07-13T21:44:51Z&quot;,
        ///			&quot;timezone&quot;: &quot;America/Los_Angeles&quot;,
        ///			&quot;duration&quot;: 60,
        ///			&quot;participant&quot;: {
        ///				&quot;user_id&quot;: &quot;31228928&quot;,
        ///				&quot;parent_user [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string meeting_breakout_room_sharing_started_webhook {
            get {
                return ResourceManager.GetString("meeting_breakout_room_sharing_started_webhook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;event&quot;: &quot;meeting.created&quot;,
        ///	&quot;event_ts&quot;: 1617628462392,
        ///	&quot;payload&quot;: {
        ///		&quot;account_id&quot;: &quot;VjZoEArIT5y-HlWxkV-tVA&quot;,
        ///		&quot;operator&quot;: &quot;someone@example.com&quot;,
        ///		&quot;operator_id&quot;: &quot;8lzIwvZTSOqjndWPbPqzuA&quot;,
        ///		&quot;object&quot;: {
        ///			&quot;uuid&quot;: &quot;5yDZGNlQSV6qOjg4NxajHQ==&quot;,
        ///			&quot;id&quot;: 98884753832,
        ///			&quot;host_id&quot;: &quot;8lzIwvZTSOqjndWPbPqzuA&quot;,
        ///			&quot;topic&quot;: &quot;ZoomNet Unit Testing: instant meeting&quot;,
        ///			&quot;type&quot;: 1,
        ///			&quot;duration&quot;: 60,
        ///			&quot;timezone&quot;: &quot;America/New_York&quot;,
        ///			&quot;join_url&quot;: &quot;https://zoom.us/j/98884753832?pwd=c21EQzg0SXY2dlNT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string meeting_created_webhook {
            get {
                return ResourceManager.GetString("meeting_created_webhook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;event&quot;: &quot;meeting.deleted&quot;,
        ///	&quot;event_ts&quot;: 1617628462764,
        ///	&quot;payload&quot;: {
        ///		&quot;account_id&quot;: &quot;VjZoEArIT5y-HlWxkV-tVA&quot;,
        ///		&quot;operator&quot;: &quot;someone@example.com&quot;,
        ///		&quot;operator_id&quot;: &quot;8lzIwvZTSOqjndWPbPqzuA&quot;,
        ///		&quot;object&quot;: {
        ///			&quot;uuid&quot;: &quot;5yDZGNlQSV6qOjg4NxajHQ==&quot;,
        ///			&quot;id&quot;: 98884753832,
        ///			&quot;host_id&quot;: &quot;8lzIwvZTSOqjndWPbPqzuA&quot;,
        ///			&quot;topic&quot;: &quot;ZoomNet Unit Testing: instant meeting&quot;,
        ///			&quot;type&quot;: 1,
        ///			&quot;duration&quot;: 60,
        ///			&quot;timezone&quot;: &quot;America/New_York&quot;
        ///		}
        ///	}
        ///}
        ///.
        /// </summary>
        internal static string meeting_deleted_webhook {
            get {
                return ResourceManager.GetString("meeting_deleted_webhook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;event&quot;: &quot;meeting.ended&quot;,
        ///	&quot;event_ts&quot;: 1626230691572,
        ///	&quot;payload&quot;: {
        ///		&quot;account_id&quot;: &quot;AAAAAABBBB&quot;,
        ///		&quot;operator&quot;: &quot;admin@example.com&quot;,
        ///		&quot;operator_id&quot;: &quot;z8yCxjabcdEFGHfp8uQ&quot;,
        ///		&quot;operation&quot;: &quot;single&quot;,
        ///		&quot;object&quot;: {
        ///			&quot;id&quot;: &quot;1234567890&quot;,
        ///			&quot;uuid&quot;: &quot;4444AAAiAAAAAiAiAiiAii==&quot;,
        ///			&quot;host_id&quot;: &quot;x1yCzABCDEfg23HiJKl4mN&quot;,
        ///			&quot;topic&quot;: &quot;My Meeting&quot;,
        ///			&quot;type&quot;: 3,
        ///			&quot;start_time&quot;: &quot;2021-07-13T21:44:51Z&quot;,
        ///			&quot;timezone&quot;: &quot;America/Los_Angeles&quot;,
        ///			&quot;duration&quot;: 60,
        ///			&quot;end_time&quot;: &quot;2021-07-13T23:00:51Z&quot;
        ///	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string meeting_ended_webhook {
            get {
                return ResourceManager.GetString("meeting_ended_webhook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;event&quot;: &quot;meeting.invitation_accepted&quot;,
        ///	&quot;event_ts&quot;: 1626230691572,
        ///	&quot;payload&quot;: {
        ///		&quot;account_id&quot;: &quot;dzVA4QmMQfyISoRcpFO8CA&quot;,
        ///		&quot;operator_id&quot;: &quot;Hy7YgA-cR4eU8EfWV00tPQ&quot;,
        ///		&quot;operator&quot;: &quot;dhill@example.com&quot;,
        ///		&quot;object&quot;: {
        ///			&quot;id&quot;: &quot;91578204824&quot;,
        ///			&quot;uuid&quot;: &quot;4444AAAiAAAAAiAiAiiAii==&quot;,
        ///			&quot;host_id&quot;: &quot;ICuPoX4ERtikRcKqkVxunQ&quot;,
        ///			&quot;topic&quot;: &quot;Jill Chill&apos;s Zoom Meeting&quot;,
        ///			&quot;participant&quot;: {
        ///				&quot;participant_user_id&quot;: &quot;rPwsQrpC6gPuw2zEJqw&quot;,
        ///				&quot;email&quot;: &quot;jchill@example.com&quot;
        ///			}
        ///		}
        ///	}
        ///}.
        /// </summary>
        internal static string meeting_invitation_accepted_webhook {
            get {
                return ResourceManager.GetString("meeting_invitation_accepted_webhook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;event&quot;: &quot;meeting.invitation_dispatched&quot;,
        ///	&quot;event_ts&quot;: 1626230691572,
        ///	&quot;payload&quot;: {
        ///		&quot;account_id&quot;: &quot;dzVA4QmMQfyISoRcpFO8CA&quot;,
        ///		&quot;operator_id&quot;: &quot;Hy7YgA-cR4eU8EfWV00tPQ&quot;,
        ///		&quot;operator&quot;: &quot;dhill@example.com&quot;,
        ///		&quot;object&quot;: {
        ///			&quot;id&quot;: &quot;91578204824&quot;,
        ///			&quot;uuid&quot;: &quot;4444AAAiAAAAAiAiAiiAii==&quot;,
        ///			&quot;host_id&quot;: &quot;ICuPoX4ERtikRcKqkVxunQ&quot;,
        ///			&quot;topic&quot;: &quot;Jill Chill&apos;s Zoom Meeting&quot;,
        ///			&quot;participant&quot;: {
        ///				&quot;participant_user_id&quot;: &quot;rPwsQrpC6gPuw2zEJqw&quot;,
        ///				&quot;email&quot;: &quot;jchill@example.com&quot;
        ///			}
        ///		}
        ///	}
        ///}.
        /// </summary>
        internal static string meeting_invitation_dispatched_webhook {
            get {
                return ResourceManager.GetString("meeting_invitation_dispatched_webhook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;event&quot;: &quot;meeting.invitation_rejected&quot;,
        ///	&quot;event_ts&quot;: 1626230691572,
        ///	&quot;payload&quot;: {
        ///		&quot;account_id&quot;: &quot;dzVA4QmMQfyISoRcpFO8CA&quot;,
        ///		&quot;operator_id&quot;: &quot;Hy7YgA-cR4eU8EfWV00tPQ&quot;,
        ///		&quot;operator&quot;: &quot;dhill@example.com&quot;,
        ///		&quot;object&quot;: {
        ///			&quot;id&quot;: &quot;91578204824&quot;,
        ///			&quot;uuid&quot;: &quot;4444AAAiAAAAAiAiAiiAii==&quot;,
        ///			&quot;host_id&quot;: &quot;ICuPoX4ERtikRcKqkVxunQ&quot;,
        ///			&quot;topic&quot;: &quot;Jill Chill&apos;s Zoom Meeting&quot;,
        ///			&quot;participant&quot;: {
        ///				&quot;participant_user_id&quot;: &quot;rPwsQrpC6gPuw2zEJqw&quot;,
        ///				&quot;email&quot;: &quot;jchill@example.com&quot;
        ///			}
        ///		}
        ///	}
        ///}.
        /// </summary>
        internal static string meeting_invitation_rejected_webhook {
            get {
                return ResourceManager.GetString("meeting_invitation_rejected_webhook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;event&quot;: &quot;meeting.invitation_timeout&quot;,
        ///	&quot;event_ts&quot;: 1626230691572,
        ///	&quot;payload&quot;: {
        ///		&quot;account_id&quot;: &quot;dzVA4QmMQfyISoRcpFO8CA&quot;,
        ///		&quot;operator_id&quot;: &quot;Hy7YgA-cR4eU8EfWV00tPQ&quot;,
        ///		&quot;operator&quot;: &quot;dhill@example.com&quot;,
        ///		&quot;object&quot;: {
        ///			&quot;id&quot;: &quot;91578204824&quot;,
        ///			&quot;uuid&quot;: &quot;4444AAAiAAAAAiAiAiiAii==&quot;,
        ///			&quot;host_id&quot;: &quot;ICuPoX4ERtikRcKqkVxunQ&quot;,
        ///			&quot;topic&quot;: &quot;Jill Chill&apos;s Zoom Meeting&quot;,
        ///			&quot;participant&quot;: {
        ///				&quot;participant_user_id&quot;: &quot;rPwsQrpC6gPuw2zEJqw&quot;,
        ///				&quot;email&quot;: &quot;jchill@example.com&quot;
        ///			}
        ///		}
        ///	}
        ///}.
        /// </summary>
        internal static string meeting_invitation_timeout_webhook {
            get {
                return ResourceManager.GetString("meeting_invitation_timeout_webhook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;event&quot;: &quot;meeting.participant_joined_breakout_room&quot;,
        ///	&quot;event_ts&quot;: 1626230691572,
        ///	&quot;payload&quot;: {
        ///		&quot;account_id&quot;: &quot;AAAAAABBBB&quot;,
        ///		&quot;object&quot;: {
        ///			&quot;id&quot;: &quot;1234567890&quot;,
        ///			&quot;uuid&quot;: &quot;4444AAAiAAAAAiAiAiiAii==&quot;,
        ///			&quot;breakout_room_uuid&quot;: &quot;FkQbpP2UR028mDrwzEahqw==&quot;,
        ///			&quot;host_id&quot;: &quot;x1yCzABCDEfg23HiJKl4mN&quot;,
        ///			&quot;topic&quot;: &quot;My Meeting&quot;,
        ///			&quot;type&quot;: 8,
        ///			&quot;start_time&quot;: &quot;2021-07-13T21:44:51Z&quot;,
        ///			&quot;timezone&quot;: &quot;America/Los_Angeles&quot;,
        ///			&quot;duration&quot;: 60,
        ///			&quot;participant&quot;: {
        ///				&quot;user_id&quot;: &quot;31228928&quot;,
        ///				&quot;parent_u [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string meeting_participant_joined_breakout_room_webhook {
            get {
                return ResourceManager.GetString("meeting_participant_joined_breakout_room_webhook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;event&quot;: &quot;meeting.participant_left_breakout_room&quot;,
        ///	&quot;event_ts&quot;: 1626230691572,
        ///	&quot;payload&quot;: {
        ///		&quot;account_id&quot;: &quot;AAAAAABBBB&quot;,
        ///		&quot;object&quot;: {
        ///			&quot;id&quot;: &quot;1234567890&quot;,
        ///			&quot;uuid&quot;: &quot;4444AAAiAAAAAiAiAiiAii==&quot;,
        ///			&quot;breakout_room_uuid&quot;: &quot;FkQbpP2UR028mDrwzEahqw==&quot;,
        ///			&quot;host_id&quot;: &quot;x1yCzABCDEfg23HiJKl4mN&quot;,
        ///			&quot;topic&quot;: &quot;My Meeting&quot;,
        ///			&quot;type&quot;: 8,
        ///			&quot;start_time&quot;: &quot;2021-07-13T21:44:51Z&quot;,
        ///			&quot;timezone&quot;: &quot;America/Los_Angeles&quot;,
        ///			&quot;duration&quot;: 60,
        ///			&quot;participant&quot;: {
        ///				&quot;user_id&quot;: &quot;31228928&quot;,
        ///				&quot;parent_use [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string meeting_participant_left_breakout_room_webhook {
            get {
                return ResourceManager.GetString("meeting_participant_left_breakout_room_webhook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;event&quot;: &quot;meeting.sharing_started&quot;,
        ///	&quot;event_ts&quot;: 1234566789900,
        ///	&quot;payload&quot;: {
        ///		&quot;account_id&quot;: &quot;EPeQtiABC000VYxHMA&quot;,
        ///		&quot;object&quot;: {
        ///			&quot;duration&quot;: 60,
        ///			&quot;start_time&quot;: &quot;2019-07-16T17:14:39Z&quot;,
        ///			&quot;timezone&quot;: &quot;America/Los_Angeles&quot;,
        ///			&quot;topic&quot;: &quot;My Meeting&quot;,
        ///			&quot;id&quot;: 6962400003,
        ///			&quot;type&quot;: 2,
        ///			&quot;uuid&quot;: &quot;4118UHIiRCAAAtBlDkcVyw==&quot;,
        ///			&quot;host_id&quot;: &quot;z8yCxTTTTSiw02QgCAp8uQ&quot;,
        ///			&quot;participant&quot;: {
        ///				&quot;id&quot;: &quot;s0AAAASoSE1V8KIFOCYw&quot;,
        ///				&quot;user_id&quot;: &quot;16778000&quot;,
        ///				&quot;user_name&quot;: &quot;Arya Arya&quot;,
        ///				&quot;sharing [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string meeting_sharing_started_webhook {
            get {
                return ResourceManager.GetString("meeting_sharing_started_webhook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;event&quot;: &quot;meeting.started&quot;,
        ///	&quot;event_ts&quot;: 1619016544371,
        ///	&quot;payload&quot;: {
        ///		&quot;account_id&quot;: &quot;VjZoEArIT5y-HlWxkV-tVA&quot;,
        ///		&quot;object&quot;: {
        ///			&quot;duration&quot;: 0,
        ///			&quot;start_time&quot;: &quot;2021-04-21T14:49:04Z&quot;,
        ///			&quot;timezone&quot;: &quot;America/New_York&quot;,
        ///			&quot;topic&quot;: &quot;My Personal Meeting Room&quot;,
        ///			&quot;id&quot;: 3479130610,
        ///			&quot;type&quot;: 4,
        ///			&quot;uuid&quot;: &quot;mOG8pEaFQqeDm6Vd/3xopA==&quot;,
        ///			&quot;host_id&quot;: &quot;8lzIwvZTSOqjndWPbPqzuA&quot;
        ///		}
        ///	}
        ///}
        ///.
        /// </summary>
        internal static string meeting_started_webhook {
            get {
                return ResourceManager.GetString("meeting_started_webhook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;event&quot;: &quot;meeting.summary_completed&quot;,
        ///	&quot;event_ts&quot;: 1626230691572,
        ///	&quot;payload&quot;: {
        ///		&quot;account_id&quot;: &quot;dzVA4QmMQfyISoRcpFO8CA&quot;,
        ///		&quot;object&quot;: {
        ///			&quot;meeting_host_id&quot;: &quot;30R7kT7bTIKSNUFEuH_Qlg&quot;,
        ///			&quot;meeting_host_email&quot;: &quot;jchill@example.com&quot;,
        ///			&quot;meeting_uuid&quot;: &quot;aDYlohsHRtCd4ii1uC2+hA==&quot;,
        ///			&quot;meeting_id&quot;: 97763643886,
        ///			&quot;meeting_topic&quot;: &quot;My Meeting&quot;,
        ///			&quot;meeting_start_time&quot;: &quot;2019-07-15T23:24:52Z&quot;,
        ///			&quot;meeting_end_time&quot;: &quot;2019-07-15T23:30:19Z&quot;,
        ///			&quot;summary_start_time&quot;: &quot;2019-07-15T23:24:52Z&quot;,
        ///			&quot;summ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string meeting_summary_completed_webhook {
            get {
                return ResourceManager.GetString("meeting_summary_completed_webhook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;event&quot;: &quot;meeting.summary_deleted&quot;,
        ///	&quot;event_ts&quot;: 1626230691572,
        ///	&quot;payload&quot;: {
        ///		&quot;account_id&quot;: &quot;dzVA4QmMQfyISoRcpFO8CA&quot;,
        ///		&quot;operator&quot;: &quot;admin@example.com&quot;,
        ///		&quot;operator_id&quot;: &quot;z8yCxjabcdEFGHfp8uQ&quot;,
        ///		&quot;object&quot;: {
        ///			&quot;meeting_host_id&quot;: &quot;30R7kT7bTIKSNUFEuH_Qlg&quot;,
        ///			&quot;meeting_host_email&quot;: &quot;jchill@example.com&quot;,
        ///			&quot;meeting_uuid&quot;: &quot;aDYlohsHRtCd4ii1uC2+hA==&quot;,
        ///			&quot;meeting_id&quot;: 97763643886,
        ///			&quot;meeting_topic&quot;: &quot;My Meeting&quot;,
        ///			&quot;meeting_start_time&quot;: &quot;2019-07-15T23:24:52Z&quot;,
        ///			&quot;meeting_end_time&quot;: &quot;2019-07 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string meeting_summary_deleted_webhook {
            get {
                return ResourceManager.GetString("meeting_summary_deleted_webhook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;event&quot;: &quot;meeting.summary_recovered&quot;,
        ///	&quot;event_ts&quot;: 1626230691572,
        ///	&quot;payload&quot;: {
        ///		&quot;account_id&quot;: &quot;dzVA4QmMQfyISoRcpFO8CA&quot;,
        ///		&quot;operator&quot;: &quot;admin@example.com&quot;,
        ///		&quot;operator_id&quot;: &quot;z8yCxjabcdEFGHfp8uQ&quot;,
        ///		&quot;object&quot;: {
        ///			&quot;meeting_host_id&quot;: &quot;30R7kT7bTIKSNUFEuH_Qlg&quot;,
        ///			&quot;meeting_host_email&quot;: &quot;jchill@example.com&quot;,
        ///			&quot;meeting_uuid&quot;: &quot;aDYlohsHRtCd4ii1uC2+hA==&quot;,
        ///			&quot;meeting_id&quot;: 97763643886,
        ///			&quot;meeting_topic&quot;: &quot;My Meeting&quot;,
        ///			&quot;meeting_start_time&quot;: &quot;2019-07-15T23:24:52Z&quot;,
        ///			&quot;meeting_end_time&quot;: &quot;2019- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string meeting_summary_recovered_webhook {
            get {
                return ResourceManager.GetString("meeting_summary_recovered_webhook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;event&quot;: &quot;meeting.summary_shared&quot;,
        ///	&quot;event_ts&quot;: 1626230691572,
        ///	&quot;payload&quot;: {
        ///		&quot;account_id&quot;: &quot;dzVA4QmMQfyISoRcpFO8CA&quot;,
        ///		&quot;operator&quot;: &quot;admin@example.com&quot;,
        ///		&quot;operator_id&quot;: &quot;z8yCxjabcdEFGHfp8uQ&quot;,
        ///		&quot;object&quot;: {
        ///			&quot;meeting_host_id&quot;: &quot;30R7kT7bTIKSNUFEuH_Qlg&quot;,
        ///			&quot;meeting_host_email&quot;: &quot;jchill@example.com&quot;,
        ///			&quot;meeting_uuid&quot;: &quot;aDYlohsHRtCd4ii1uC2+hA==&quot;,
        ///			&quot;meeting_id&quot;: 97763643886,
        ///			&quot;meeting_topic&quot;: &quot;My Meeting&quot;,
        ///			&quot;meeting_start_time&quot;: &quot;2019-07-15T23:24:52Z&quot;,
        ///			&quot;meeting_end_time&quot;: &quot;2019-07- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string meeting_summary_shared_webhook {
            get {
                return ResourceManager.GetString("meeting_summary_shared_webhook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;event&quot;: &quot;meeting.summary_trashed&quot;,
        ///	&quot;event_ts&quot;: 1626230691572,
        ///	&quot;payload&quot;: {
        ///		&quot;account_id&quot;: &quot;dzVA4QmMQfyISoRcpFO8CA&quot;,
        ///		&quot;operator&quot;: &quot;admin@example.com&quot;,
        ///		&quot;operator_id&quot;: &quot;z8yCxjabcdEFGHfp8uQ&quot;,
        ///		&quot;object&quot;: {
        ///			&quot;meeting_host_id&quot;: &quot;30R7kT7bTIKSNUFEuH_Qlg&quot;,
        ///			&quot;meeting_host_email&quot;: &quot;jchill@example.com&quot;,
        ///			&quot;meeting_uuid&quot;: &quot;aDYlohsHRtCd4ii1uC2+hA==&quot;,
        ///			&quot;meeting_id&quot;: 97763643886,
        ///			&quot;meeting_topic&quot;: &quot;My Meeting&quot;,
        ///			&quot;meeting_start_time&quot;: &quot;2019-07-15T23:24:52Z&quot;,
        ///			&quot;meeting_end_time&quot;: &quot;2019-07 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string meeting_summary_trashed_webhook {
            get {
                return ResourceManager.GetString("meeting_summary_trashed_webhook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;event&quot;: &quot;meeting.summary_updated&quot;,
        ///	&quot;event_ts&quot;: 1626230691572,
        ///	&quot;payload&quot;: {
        ///		&quot;account_id&quot;: &quot;dzVA4QmMQfyISoRcpFO8CA&quot;,
        ///		&quot;operator&quot;: &quot;admin@example.com&quot;,
        ///		&quot;operator_id&quot;: &quot;z8yCxjabcdEFGHfp8uQ&quot;,
        ///		&quot;object&quot;: {
        ///			&quot;meeting_host_id&quot;: &quot;30R7kT7bTIKSNUFEuH_Qlg&quot;,
        ///			&quot;meeting_host_email&quot;: &quot;jchill@example.com&quot;,
        ///			&quot;meeting_uuid&quot;: &quot;aDYlohsHRtCd4ii1uC2+hA==&quot;,
        ///			&quot;meeting_id&quot;: 97763643886,
        ///			&quot;meeting_topic&quot;: &quot;My Meeting&quot;,
        ///			&quot;meeting_start_time&quot;: &quot;2019-07-15T23:24:52Z&quot;,
        ///			&quot;meeting_end_time&quot;: &quot;2019-07 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string meeting_summary_updated_webhook {
            get {
                return ResourceManager.GetString("meeting_summary_updated_webhook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;event&quot;: &quot;meeting.updated&quot;,
        ///	&quot;event_ts&quot;: 1617628464664,
        ///	&quot;payload&quot;: {
        ///		&quot;account_id&quot;: &quot;VjZoEArIT5y-HlWxkV-tVA&quot;,
        ///		&quot;operator&quot;: &quot;someone@example.com&quot;,
        ///		&quot;operator_id&quot;: &quot;8lzIwvZTSOqjndWPbPqzuA&quot;,
        ///		&quot;object&quot;: {
        ///			&quot;id&quot;: 94890226305,
        ///			&quot;topic&quot;: &quot;ZoomNet Unit Testing: UPDATED scheduled meeting&quot;,
        ///			&quot;settings&quot;: { &quot;audio&quot;: &quot;voip&quot; }
        ///			},
        ///		&quot;old_object&quot;: {
        ///			&quot;id&quot;: 94890226305,
        ///			&quot;topic&quot;: &quot;ZoomNet Unit Testing: scheduled meeting&quot;,
        ///			&quot;settings&quot;: { &quot;audio&quot;: &quot;telephony&quot; }
        ///		},
        ///		&quot;time_stamp&quot;: 1617 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string meeting_updated_webhook {
            get {
                return ResourceManager.GetString("meeting_updated_webhook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;event&quot;: &quot;recording.completed&quot;,
        ///	&quot;event_ts&quot;: 1626230691572,
        ///	&quot;download_token&quot;: &quot;abJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJodHRwczovL2V2ZW50Lnpvb20udXMiLCJhY2NvdW50SWQiOiJNdDZzdjR1MFRBeVBrd2dzTDJseGlBIiwiYXVkIjoiaHR0cHM6Ly9vYXV0aC56b29tLnVzIiwibWlkIjoieFp3SEc0c3BRU2VuekdZWG16dnpiUT09IiwiZXhwIjoxNjI2MTM5NTA3LCJ1c2VySWQiOiJEWUhyZHBqclMzdWFPZjdkUGtrZzh3In0.a6KetiC6BlkDhf1dP4KBGUE1bb2brMeraoD45yhFx0eSSSTFdkHQnsKmlJQ-hdo9Zy-4vQw3rOxlyoHv583JyZ&quot;,
        ///	&quot;payload&quot;: {
        ///		&quot;account_id&quot;: &quot;AAAAAABBBB&quot;,
        ///		&quot;object&quot;: {
        ///			&quot;id&quot;: 1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string recording_completed_webhook {
            get {
                return ResourceManager.GetString("recording_completed_webhook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;event&quot;: &quot;webinar.ended&quot;,
        ///	&quot;event_ts&quot;: 1626230691572,
        ///	&quot;payload&quot;: {
        ///		&quot;account_id&quot;: &quot;AAAAAABBBB&quot;,
        ///		&quot;object&quot;: {
        ///			&quot;id&quot;: &quot;1234567890&quot;,
        ///			&quot;uuid&quot;: &quot;4444AAAiAAAAAiAiAiiAii==&quot;,
        ///			&quot;host_id&quot;: &quot;x1yCzABCDEfg23HiJKl4mN&quot;,
        ///			&quot;topic&quot;: &quot;My Webinar&quot;,
        ///			&quot;type&quot;: 5,
        ///			&quot;start_time&quot;: &quot;2021-07-13T21:44:51Z&quot;,
        ///			&quot;timezone&quot;: &quot;America/Los_Angeles&quot;,
        ///			&quot;duration&quot;: 60,
        ///			&quot;end_time&quot;: &quot;2021-07-13T23:00:51Z&quot;
        ///		}
        ///	}
        ///}.
        /// </summary>
        internal static string webinar_ended_webhook {
            get {
                return ResourceManager.GetString("webinar_ended_webhook", resourceCulture);
            }
        }
    }
}
