using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace ZoomNet.Json
{
	[JsonSerializable(typeof(System.Text.Json.Nodes.JsonObject))]
	[JsonSerializable(typeof(System.Text.Json.Nodes.JsonObject[]))]

	[JsonSerializable(typeof(ZoomNet.Models.Account))]
	[JsonSerializable(typeof(ZoomNet.Models.ApprovalType))]
	[JsonSerializable(typeof(ZoomNet.Models.Assistant))]
	[JsonSerializable(typeof(ZoomNet.Models.AttendeeChatSaveType))]
	[JsonSerializable(typeof(ZoomNet.Models.AttendeeChatType))]
	[JsonSerializable(typeof(ZoomNet.Models.AudioConferencingCallSettings))]
	[JsonSerializable(typeof(ZoomNet.Models.AudioConferencingPhoneNumberInformation))]
	[JsonSerializable(typeof(ZoomNet.Models.AudioConferencingUserSettings))]
	[JsonSerializable(typeof(ZoomNet.Models.AudioType))]
	[JsonSerializable(typeof(ZoomNet.Models.AuthenticationOptions))]
	[JsonSerializable(typeof(ZoomNet.Models.AuthenticationSettings))]
	[JsonSerializable(typeof(ZoomNet.Models.AuthenticationType))]
	[JsonSerializable(typeof(ZoomNet.Models.BatchRegistrant))]
	[JsonSerializable(typeof(IEnumerable<ZoomNet.Models.BatchRegistrant>))]
	[JsonSerializable(typeof(ZoomNet.Models.BatchRegistrantInfo))]
	[JsonSerializable(typeof(ZoomNet.Models.BatchRegistrantInfo[]))]
	[JsonSerializable(typeof(ZoomNet.Models.CallLog))]
	[JsonSerializable(typeof(ZoomNet.Models.CallLogCalleeNumberType))]
	[JsonSerializable(typeof(ZoomNet.Models.CallLogCallerNumberType))]
	[JsonSerializable(typeof(ZoomNet.Models.CallLogCallType))]
	[JsonSerializable(typeof(ZoomNet.Models.CallLogDirection))]
	[JsonSerializable(typeof(ZoomNet.Models.CallLogNumberSource))]
	[JsonSerializable(typeof(ZoomNet.Models.CallLogResult))]
	[JsonSerializable(typeof(ZoomNet.Models.CallLogSite))]
	[JsonSerializable(typeof(ZoomNet.Models.CallLogTransferInfo))]
	[JsonSerializable(typeof(ZoomNet.Models.CallLogTransferInfoExtensionType))]
	[JsonSerializable(typeof(ZoomNet.Models.CallLogTransferInfoNumberType))]
	[JsonSerializable(typeof(ZoomNet.Models.CallLogType))]
	[JsonSerializable(typeof(ZoomNet.Models.ChatChannel))]
	[JsonSerializable(typeof(ZoomNet.Models.ChatChannelMember))]
	[JsonSerializable(typeof(ZoomNet.Models.ChatChannelRole))]
	[JsonSerializable(typeof(ZoomNet.Models.ChatChannelSettings))]
	[JsonSerializable(typeof(ZoomNet.Models.ChatChannelType))]
	[JsonSerializable(typeof(ZoomNet.Models.ChatMention))]
	[JsonSerializable(typeof(ZoomNet.Models.ChatMentionType))]
	[JsonSerializable(typeof(ZoomNet.Models.ChatMessage))]
	[JsonSerializable(typeof(ZoomNet.Models.ChimeType))]
	[JsonSerializable(typeof(ZoomNet.Models.ClientFeedbackDetail))]
	[JsonSerializable(typeof(ZoomNet.Models.ClientFeedbackMetrics))]
	[JsonSerializable(typeof(ZoomNet.Models.ClientFeedbackMetricsReport))]
	[JsonSerializable(typeof(ZoomNet.Models.ClientSatisfactionMetrics))]
	[JsonSerializable(typeof(ZoomNet.Models.ClientSatisfactionReport))]
	[JsonSerializable(typeof(ZoomNet.Models.ClosedCaptioningSettings))]
	[JsonSerializable(typeof(ZoomNet.Models.ConcurrentMeetingType))]
	[JsonSerializable(typeof(ZoomNet.Models.Contact))]
	[JsonSerializable(typeof(ZoomNet.Models.ContactType))]
	[JsonSerializable(typeof(ZoomNet.Models.Country))]
	[JsonSerializable(typeof(ZoomNet.Models.CrcPortMetrics))]
	[JsonSerializable(typeof(ZoomNet.Models.CrcPortsHourUsage))]
	[JsonSerializable(typeof(ZoomNet.Models.CrcPortsUsage))]
	[JsonSerializable(typeof(ZoomNet.Models.CustomAttribute))]
	[JsonSerializable(typeof(ZoomNet.Models.DashboardMeetingMetrics))]
	[JsonSerializable(typeof(ZoomNet.Models.DashboardMeetingMetricsPaginationObject))]
	[JsonSerializable(typeof(ZoomNet.Models.DashboardMeetingParticipant))]
	[JsonSerializable(typeof(ZoomNet.Models.DashboardMeetingParticipantQos))]
	[JsonSerializable(typeof(ZoomNet.Models.DashboardMeetingType))]
	[JsonSerializable(typeof(ZoomNet.Models.DashboardMetricsBase))]
	[JsonSerializable(typeof(ZoomNet.Models.DashboardParticipant))]
	[JsonSerializable(typeof(ZoomNet.Models.DashboardParticipantQos))]
	[JsonSerializable(typeof(ZoomNet.Models.DataCenterRegion))]
	[JsonSerializable(typeof(ZoomNet.Models.EmailNotificationUserSettings))]
	[JsonSerializable(typeof(ZoomNet.Models.EncryptionType))]
	[JsonSerializable(typeof(ZoomNet.Models.FeatureUserSettings))]
	[JsonSerializable(typeof(ZoomNet.Models.ImMetric))]
	[JsonSerializable(typeof(ZoomNet.Models.InstantMeeting))]
	[JsonSerializable(typeof(ZoomNet.Models.InstantMeetingUserSettings))]
	[JsonSerializable(typeof(ZoomNet.Models.InterpretationLanguage))]
	[JsonSerializable(typeof(ZoomNet.Models.InviteLink))]
	[JsonSerializable(typeof(ZoomNet.Models.IpAddressAccessControlSettings))]
	[JsonSerializable(typeof(ZoomNet.Models.IssuesOfZoomRooms))]
	[JsonSerializable(typeof(ZoomNet.Models.IssuesOfZoomRoomsReport))]
	[JsonSerializable(typeof(ZoomNet.Models.IssueType))]
	[JsonSerializable(typeof(ZoomNet.Models.JoinBeforeHostTime))]
	[JsonSerializable(typeof(ZoomNet.Models.Language))]
	[JsonSerializable(typeof(ZoomNet.Models.LanguageInterpretationSettings))]
	[JsonSerializable(typeof(ZoomNet.Models.LiveStreamingInfo))]
	[JsonSerializable(typeof(ZoomNet.Models.LiveStreamingSettings))]
	[JsonSerializable(typeof(ZoomNet.Models.LoginType))]
	[JsonSerializable(typeof(ZoomNet.Models.ManualCaptioningSettings))]
	[JsonSerializable(typeof(ZoomNet.Models.Meeting))]
	[JsonSerializable(typeof(ZoomNet.Models.MeetingFile))]
	[JsonSerializable(typeof(ZoomNet.Models.MeetingListType))]
	[JsonSerializable(typeof(ZoomNet.Models.MeetingOccurrence))]
	[JsonSerializable(typeof(ZoomNet.Models.MeetingSettings))]
	[JsonSerializable(typeof(ZoomNet.Models.MeetingStatus))]
	[JsonSerializable(typeof(ZoomNet.Models.MeetingSummary))]
	[JsonSerializable(typeof(ZoomNet.Models.MeetingTemplate))]
	[JsonSerializable(typeof(ZoomNet.Models.MeetingTemplateType))]
	[JsonSerializable(typeof(ZoomNet.Models.MeetingType))]
	[JsonSerializable(typeof(ZoomNet.Models.NumberOfEmployees))]
	[JsonSerializable(typeof(ZoomNet.Models.OAuthGrantType))]
	[JsonSerializable(typeof(ZoomNet.Models.Panelist))]
	[JsonSerializable(typeof(ZoomNet.Models.Participant))]
	[JsonSerializable(typeof(ZoomNet.Models.ParticipantChatSaveType))]
	[JsonSerializable(typeof(ZoomNet.Models.ParticipantChatType))]
	[JsonSerializable(typeof(ZoomNet.Models.ParticipantDevice))]
	[JsonSerializable(typeof(ZoomNet.Models.ParticipantNetwork))]
	[JsonSerializable(typeof(ZoomNet.Models.ParticipantSharingDetails))]
	[JsonSerializable(typeof(ZoomNet.Models.ParticipantStatus))]
	[JsonSerializable(typeof(ZoomNet.Models.ParticipantsToPlaceInWaitingRoom))]
	[JsonSerializable(typeof(ZoomNet.Models.PasswordRequirements))]
	[JsonSerializable(typeof(ZoomNet.Models.PastInstance))]
	[JsonSerializable(typeof(ZoomNet.Models.PastMeeting))]
	[JsonSerializable(typeof(ZoomNet.Models.PayMode))]
	[JsonSerializable(typeof(ZoomNet.Models.PhoneNumber))]
	[JsonSerializable(typeof(ZoomNet.Models.PhoneType))]
	[JsonSerializable(typeof(ZoomNet.Models.PmiMeetingPasswordRequirementType))]
	[JsonSerializable(typeof(ZoomNet.Models.Poll))]
	[JsonSerializable(typeof(ZoomNet.Models.PollAnswer))]
	[JsonSerializable(typeof(ZoomNet.Models.PollPrompt))]
	[JsonSerializable(typeof(ZoomNet.Models.PollQuestion))]
	[JsonSerializable(typeof(ZoomNet.Models.PollQuestionType))]
	[JsonSerializable(typeof(ZoomNet.Models.PollResult))]
	[JsonSerializable(typeof(ZoomNet.Models.PollStatus))]
	[JsonSerializable(typeof(ZoomNet.Models.PollType))]
	[JsonSerializable(typeof(ZoomNet.Models.PresenceStatus))]
	[JsonSerializable(typeof(ZoomNet.Models.PronounDisplayType))]
	[JsonSerializable(typeof(ZoomNet.Models.PurchasingTimeFrame))]
	[JsonSerializable(typeof(ZoomNet.Models.QualityOfService.CpuUsage), TypeInfoPropertyName = "QualityOfServiceCpuUsage")]
	[JsonSerializable(typeof(ZoomNet.Models.QualityOfService.PacketQualityOfServiceMetrics), TypeInfoPropertyName = "QualityOfServicePacketQualityOfServiceMetrics")]
	[JsonSerializable(typeof(ZoomNet.Models.QualityOfService.VideoQualityOfServiceMetrics), TypeInfoPropertyName = "QualityOfServiceVideoQualityOfServiceMetrics")]
	[JsonSerializable(typeof(ZoomNet.Models.QualityType))]
	[JsonSerializable(typeof(ZoomNet.Models.Recording))]
	[JsonSerializable(typeof(ZoomNet.Models.RecordingContentType))]
	[JsonSerializable(typeof(ZoomNet.Models.RecordingFile))]
	[JsonSerializable(typeof(ZoomNet.Models.RecordingFileType))]
	[JsonSerializable(typeof(ZoomNet.Models.RecordingRegistration))]
	[JsonSerializable(typeof(ZoomNet.Models.RecordingSettings))]
	[JsonSerializable(typeof(ZoomNet.Models.RecordingSharingType))]
	[JsonSerializable(typeof(ZoomNet.Models.RecordingType))]
	[JsonSerializable(typeof(ZoomNet.Models.RecordingUserSettings))]
	[JsonSerializable(typeof(ZoomNet.Models.RecurrenceInfo))]
	[JsonSerializable(typeof(ZoomNet.Models.RecurrenceType))]
	[JsonSerializable(typeof(ZoomNet.Models.RecurringMeeting))]
	[JsonSerializable(typeof(ZoomNet.Models.RecurringWebinar))]
	[JsonSerializable(typeof(ZoomNet.Models.Registrant))]
	[JsonSerializable(typeof(ZoomNet.Models.RegistrantInfo))]
	[JsonSerializable(typeof(ZoomNet.Models.RegistrantStatus))]
	[JsonSerializable(typeof(ZoomNet.Models.RegistrationAnswer))]
	[JsonSerializable(typeof(ZoomNet.Models.RegistrationCustomQuestionForMeeting))]
	[JsonSerializable(typeof(ZoomNet.Models.RegistrationCustomQuestionForWebinar))]
	[JsonSerializable(typeof(ZoomNet.Models.RegistrationCustomQuestionTypeForMeeting))]
	[JsonSerializable(typeof(ZoomNet.Models.RegistrationCustomQuestionTypeForWebinar))]
	[JsonSerializable(typeof(ZoomNet.Models.RegistrationField))]
	[JsonSerializable(typeof(ZoomNet.Models.RegistrationQuestionsForMeeting))]
	[JsonSerializable(typeof(ZoomNet.Models.RegistrationQuestionsForWebinar))]
	[JsonSerializable(typeof(ZoomNet.Models.RegistrationType))]
	[JsonSerializable(typeof(ZoomNet.Models.ReportHost))]
	[JsonSerializable(typeof(ZoomNet.Models.ReportHostType))]
	[JsonSerializable(typeof(ZoomNet.Models.ReportMeetingParticipant))]
	[JsonSerializable(typeof(ZoomNet.Models.ReportMeetingType))]
	[JsonSerializable(typeof(ZoomNet.Models.ReportParticipant))]
	[JsonSerializable(typeof(ZoomNet.Models.Role))]
	[JsonSerializable(typeof(ZoomNet.Models.RoleInPurchaseProcess))]
	[JsonSerializable(typeof(ZoomNet.Models.ScheduledMeeting))]
	[JsonSerializable(typeof(ZoomNet.Models.ScheduledMeetingUserSettings))]
	[JsonSerializable(typeof(ZoomNet.Models.ScheduledWebinar))]
	[JsonSerializable(typeof(ZoomNet.Models.ScreenshareContentType))]
	[JsonSerializable(typeof(ZoomNet.Models.ScreenshareDetails))]
	[JsonSerializable(typeof(ZoomNet.Models.SecuritySettings))]
	[JsonSerializable(typeof(ZoomNet.Models.SharingAndRecordingDetail))]
	[JsonSerializable(typeof(ZoomNet.Models.StreamingService))]
	[JsonSerializable(typeof(ZoomNet.Models.Survey))]
	[JsonSerializable(typeof(ZoomNet.Models.SurveyDetails))]
	[JsonSerializable(typeof(ZoomNet.Models.SurveyQuestion))]
	[JsonSerializable(typeof(ZoomNet.Models.SurveyQuestionType))]
	[JsonSerializable(typeof(ZoomNet.Models.TelephonyRegionsSettings))]
	[JsonSerializable(typeof(ZoomNet.Models.TelephonyUserSettings))]
	[JsonSerializable(typeof(ZoomNet.Models.TimeZones))]
	[JsonSerializable(typeof(ZoomNet.Models.TrackingSource))]
	[JsonSerializable(typeof(ZoomNet.Models.TspUserSettings))]
	[JsonSerializable(typeof(ZoomNet.Models.User))]
	[JsonSerializable(typeof(ZoomNet.Models.UserCallLog))]
	[JsonSerializable(typeof(ZoomNet.Models.UserCreateType))]
	[JsonSerializable(typeof(ZoomNet.Models.UserProfile))]
	[JsonSerializable(typeof(ZoomNet.Models.UserRecordingStorageSettings))]
	[JsonSerializable(typeof(ZoomNet.Models.UserSettings))]
	[JsonSerializable(typeof(ZoomNet.Models.UserStatus))]
	[JsonSerializable(typeof(ZoomNet.Models.UsersWhoCanAdmitParticipantsFromWaitingRoom))]
	[JsonSerializable(typeof(ZoomNet.Models.UserType))]
	[JsonSerializable(typeof(ZoomNet.Models.VirtualBackgroundFile))]
	[JsonSerializable(typeof(ZoomNet.Models.VirtualBackgroundSettings))]
	[JsonSerializable(typeof(ZoomNet.Models.VirtualBackgroundType))]
	[JsonSerializable(typeof(ZoomNet.Models.WaitingRoomSettings))]
	[JsonSerializable(typeof(ZoomNet.Models.WebhookParticipant))]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.AppDeauthorizedEvent), TypeInfoPropertyName = "WebhooksAppDeauthorizedEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.EndpointUrlValidationEvent), TypeInfoPropertyName = "WebhooksEndpointUrlValidationEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.Event), TypeInfoPropertyName = "WebhooksEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.EventType), TypeInfoPropertyName = "WebhooksEventType")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingCreatedEvent), TypeInfoPropertyName = "WebhooksMeetingCreatedEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingDeletedEvent), TypeInfoPropertyName = "WebhooksMeetingDeletedEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingEndedEvent), TypeInfoPropertyName = "WebhooksMeetingEndedEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingEvent), TypeInfoPropertyName = "WebhooksMeetingEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingLiveStreamStartedEvent), TypeInfoPropertyName = "WebhooksMeetingLiveStreamStartedEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingLiveStreamStoppedEvent), TypeInfoPropertyName = "WebhooksMeetingLiveStreamStoppedEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingParticipantAdmittedEvent), TypeInfoPropertyName = "WebhooksMeetingParticipantAdmittedEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingParticipantJoinedBeforeHostEvent), TypeInfoPropertyName = "WebhooksMeetingParticipantJoinedBeforeHostEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingParticipantJoinedEvent), TypeInfoPropertyName = "WebhooksMeetingParticipantJoinedEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingParticipantJoinedWaitingRoomEvent), TypeInfoPropertyName = "WebhooksMeetingParticipantJoinedWaitingRoomEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingParticipantLeftEvent), TypeInfoPropertyName = "WebhooksMeetingParticipantLeftEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingParticipantLeftWaitingRoomEvent), TypeInfoPropertyName = "WebhooksMeetingParticipantLeftWaitingRoomEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingParticipantSentToWaitingRoomEvent), TypeInfoPropertyName = "WebhooksMeetingParticipantSentToWaitingRoomEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingParticipantWaitingForHostEvent), TypeInfoPropertyName = "WebhooksMeetingParticipantWaitingForHostEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingPermanentlyDeletedEvent), TypeInfoPropertyName = "WebhooksMeetingPermanentlyDeletedEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingRecoveredEvent), TypeInfoPropertyName = "WebhooksMeetingRecoveredEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingRegistrationApprovedEvent), TypeInfoPropertyName = "WebhooksMeetingRegistrationApprovedEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingRegistrationCancelledEvent), TypeInfoPropertyName = "WebhooksMeetingRegistrationCancelledEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingRegistrationCreatedEvent), TypeInfoPropertyName = "WebhooksMeetingRegistrationCreatedEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingRegistrationDeniedEvent), TypeInfoPropertyName = "WebhooksMeetingRegistrationDeniedEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingServiceIssueEvent), TypeInfoPropertyName = "WebhooksMeetingServiceIssueEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingSharingEndedEvent), TypeInfoPropertyName = "WebhooksMeetingSharingEndedEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingSharingStartedEvent), TypeInfoPropertyName = "WebhooksMeetingSharingStartedEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingStartedEvent), TypeInfoPropertyName = "WebhooksMeetingStartedEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingUpdatedEvent), TypeInfoPropertyName = "WebhooksMeetingUpdatedEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.WebinarCreatedEvent), TypeInfoPropertyName = "WebhooksWebinarCreatedEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.WebinarDeletedEvent), TypeInfoPropertyName = "WebhooksWebinarDeletedEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.WebinarEndedEvent), TypeInfoPropertyName = "WebhooksWebinarEndedEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.WebinarEvent), TypeInfoPropertyName = "WebhooksWebinarEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.WebinarParticipantJoinedEvent), TypeInfoPropertyName = "WebhooksWebinarParticipantJoinedEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.WebinarParticipantLeftEvent), TypeInfoPropertyName = "WebhooksWebinarParticipantLeftEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.WebinarRegistrationApprovedEvent), TypeInfoPropertyName = "WebhooksWebinarRegistrationApprovedEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.WebinarRegistrationCancelledEvent), TypeInfoPropertyName = "WebhooksWebinarRegistrationCancelledEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.WebinarRegistrationCreatedEvent), TypeInfoPropertyName = "WebhooksWebinarRegistrationCreatedEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.WebinarRegistrationDeniedEvent), TypeInfoPropertyName = "WebhooksWebinarRegistrationDeniedEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.WebinarServiceIssueEvent), TypeInfoPropertyName = "WebhooksWebinarServiceIssueEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.WebinarSharingEndedEvent), TypeInfoPropertyName = "WebhooksWebinarSharingEndedEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.WebinarSharingStartedEvent), TypeInfoPropertyName = "WebhooksWebinarSharingStartedEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.WebinarStartedEvent), TypeInfoPropertyName = "WebhooksWebinarStartedEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.WebinarUpdatedEvent), TypeInfoPropertyName = "WebhooksWebinarUpdatedEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webinar))]
	[JsonSerializable(typeof(ZoomNet.Models.WebinarChatSettings))]
	[JsonSerializable(typeof(ZoomNet.Models.WebinarChatType))]
	[JsonSerializable(typeof(ZoomNet.Models.WebinarLiveStreamingSettings))]
	[JsonSerializable(typeof(ZoomNet.Models.WebinarPollingSettings))]
	[JsonSerializable(typeof(ZoomNet.Models.WebinarSettings))]
	[JsonSerializable(typeof(ZoomNet.Models.WebinarSummary))]
	[JsonSerializable(typeof(ZoomNet.Models.WebinarTemplate))]
	[JsonSerializable(typeof(ZoomNet.Models.WebinarType))]
	[JsonSerializable(typeof(ZoomNet.Models.WhoCanShare))]
	[JsonSerializable(typeof(ZoomNet.Models.ZoomRoom))]
	[JsonSerializable(typeof(ZoomNet.Models.ZoomRoomIssueDetails))]
	[JsonSerializable(typeof(ZoomNet.Models.ZoomRoomWithIssues))]
	[JsonSerializable(typeof(ZoomNet.Models.ZoomRoomWithIssuesReport))]

	[JsonSerializable(typeof(ZoomNet.Models.Account[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ApprovalType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.Assistant[]))]
	[JsonSerializable(typeof(ZoomNet.Models.AttendeeChatSaveType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.AttendeeChatType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.AudioConferencingCallSettings[]))]
	[JsonSerializable(typeof(ZoomNet.Models.AudioConferencingPhoneNumberInformation[]))]
	[JsonSerializable(typeof(ZoomNet.Models.AudioConferencingUserSettings[]))]
	[JsonSerializable(typeof(ZoomNet.Models.AudioType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.AuthenticationOptions[]))]
	[JsonSerializable(typeof(ZoomNet.Models.AuthenticationSettings[]))]
	[JsonSerializable(typeof(ZoomNet.Models.AuthenticationType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.CallLog[]))]
	[JsonSerializable(typeof(ZoomNet.Models.CallLogCalleeNumberType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.CallLogCallerNumberType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.CallLogCallType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.CallLogDirection[]))]
	[JsonSerializable(typeof(ZoomNet.Models.CallLogNumberSource[]))]
	[JsonSerializable(typeof(ZoomNet.Models.CallLogResult[]))]
	[JsonSerializable(typeof(ZoomNet.Models.CallLogSite[]))]
	[JsonSerializable(typeof(ZoomNet.Models.CallLogTransferInfo[]))]
	[JsonSerializable(typeof(ZoomNet.Models.CallLogTransferInfoExtensionType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.CallLogTransferInfoNumberType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.CallLogType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ChatChannel[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ChatChannelMember[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ChatChannelRole[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ChatChannelSettings[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ChatChannelType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ChatMention[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ChatMentionType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ChatMessage[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ChimeType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ClientFeedbackDetail[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ClientFeedbackMetrics[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ClientFeedbackMetricsReport[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ClientSatisfactionMetrics[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ClientSatisfactionReport[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ClosedCaptioningSettings[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ConcurrentMeetingType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.Contact[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ContactType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.Country[]))]
	[JsonSerializable(typeof(ZoomNet.Models.CrcPortMetrics[]))]
	[JsonSerializable(typeof(ZoomNet.Models.CrcPortsHourUsage[]))]
	[JsonSerializable(typeof(ZoomNet.Models.CrcPortsUsage[]))]
	[JsonSerializable(typeof(ZoomNet.Models.CustomAttribute[]))]
	[JsonSerializable(typeof(ZoomNet.Models.DashboardMeetingMetrics[]))]
	[JsonSerializable(typeof(ZoomNet.Models.DashboardMeetingMetricsPaginationObject[]))]
	[JsonSerializable(typeof(ZoomNet.Models.DashboardMeetingParticipant[]))]
	[JsonSerializable(typeof(ZoomNet.Models.DashboardMeetingParticipantQos[]))]
	[JsonSerializable(typeof(ZoomNet.Models.DashboardMeetingType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.DashboardMetricsBase[]))]
	[JsonSerializable(typeof(ZoomNet.Models.DashboardParticipant[]))]
	[JsonSerializable(typeof(ZoomNet.Models.DashboardParticipantQos[]))]
	[JsonSerializable(typeof(ZoomNet.Models.DataCenterRegion[]))]
	[JsonSerializable(typeof(ZoomNet.Models.EmailNotificationUserSettings[]))]
	[JsonSerializable(typeof(ZoomNet.Models.EncryptionType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.FeatureUserSettings[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ImMetric[]))]
	[JsonSerializable(typeof(ZoomNet.Models.InstantMeeting[]))]
	[JsonSerializable(typeof(ZoomNet.Models.InstantMeetingUserSettings[]))]
	[JsonSerializable(typeof(ZoomNet.Models.InterpretationLanguage[]))]
	[JsonSerializable(typeof(ZoomNet.Models.InviteLink[]))]
	[JsonSerializable(typeof(ZoomNet.Models.IpAddressAccessControlSettings[]))]
	[JsonSerializable(typeof(ZoomNet.Models.IssuesOfZoomRooms[]))]
	[JsonSerializable(typeof(ZoomNet.Models.IssuesOfZoomRoomsReport[]))]
	[JsonSerializable(typeof(ZoomNet.Models.IssueType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.JoinBeforeHostTime[]))]
	[JsonSerializable(typeof(ZoomNet.Models.Language[]))]
	[JsonSerializable(typeof(ZoomNet.Models.LanguageInterpretationSettings[]))]
	[JsonSerializable(typeof(ZoomNet.Models.LiveStreamingInfo[]))]
	[JsonSerializable(typeof(ZoomNet.Models.LiveStreamingSettings[]))]
	[JsonSerializable(typeof(ZoomNet.Models.LoginType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ManualCaptioningSettings[]))]
	[JsonSerializable(typeof(ZoomNet.Models.Meeting[]))]
	[JsonSerializable(typeof(ZoomNet.Models.MeetingFile[]))]
	[JsonSerializable(typeof(ZoomNet.Models.MeetingListType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.MeetingOccurrence[]))]
	[JsonSerializable(typeof(ZoomNet.Models.MeetingSettings[]))]
	[JsonSerializable(typeof(ZoomNet.Models.MeetingStatus[]))]
	[JsonSerializable(typeof(ZoomNet.Models.MeetingSummary[]))]
	[JsonSerializable(typeof(ZoomNet.Models.MeetingTemplate[]))]
	[JsonSerializable(typeof(ZoomNet.Models.MeetingTemplateType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.MeetingType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.NumberOfEmployees[]))]
	[JsonSerializable(typeof(ZoomNet.Models.OAuthGrantType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.Panelist[]))]
	[JsonSerializable(typeof(ZoomNet.Models.Participant[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ParticipantChatSaveType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ParticipantChatType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ParticipantDevice[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ParticipantNetwork[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ParticipantSharingDetails[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ParticipantStatus[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ParticipantsToPlaceInWaitingRoom[]))]
	[JsonSerializable(typeof(ZoomNet.Models.PasswordRequirements[]))]
	[JsonSerializable(typeof(ZoomNet.Models.PastInstance[]))]
	[JsonSerializable(typeof(ZoomNet.Models.PastMeeting[]))]
	[JsonSerializable(typeof(ZoomNet.Models.PayMode[]))]
	[JsonSerializable(typeof(ZoomNet.Models.PhoneNumber[]))]
	[JsonSerializable(typeof(ZoomNet.Models.PhoneType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.PmiMeetingPasswordRequirementType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.Poll[]))]
	[JsonSerializable(typeof(ZoomNet.Models.PollAnswer[]))]
	[JsonSerializable(typeof(ZoomNet.Models.PollPrompt[]))]
	[JsonSerializable(typeof(ZoomNet.Models.PollQuestion[]))]
	[JsonSerializable(typeof(ZoomNet.Models.PollQuestionType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.PollResult[]))]
	[JsonSerializable(typeof(ZoomNet.Models.PollStatus[]))]
	[JsonSerializable(typeof(ZoomNet.Models.PollType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.PresenceStatus[]))]
	[JsonSerializable(typeof(ZoomNet.Models.PronounDisplayType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.PurchasingTimeFrame[]))]
	[JsonSerializable(typeof(ZoomNet.Models.QualityOfService.CpuUsage[]), TypeInfoPropertyName = "QualityOfServiceCpuUsageArray")]
	[JsonSerializable(typeof(ZoomNet.Models.QualityOfService.PacketQualityOfServiceMetrics[]), TypeInfoPropertyName = "QualityOfServicePacketQualityOfServiceMetricsArray")]
	[JsonSerializable(typeof(ZoomNet.Models.QualityOfService.VideoQualityOfServiceMetrics[]), TypeInfoPropertyName = "QualityOfServiceVideoQualityOfServiceMetricsArray")]
	[JsonSerializable(typeof(ZoomNet.Models.QualityType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.Recording[]))]
	[JsonSerializable(typeof(ZoomNet.Models.RecordingContentType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.RecordingFile[]))]
	[JsonSerializable(typeof(ZoomNet.Models.RecordingFileType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.RecordingRegistration[]))]
	[JsonSerializable(typeof(ZoomNet.Models.RecordingSettings[]))]
	[JsonSerializable(typeof(ZoomNet.Models.RecordingSharingType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.RecordingType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.RecordingUserSettings[]))]
	[JsonSerializable(typeof(ZoomNet.Models.RecurrenceInfo[]))]
	[JsonSerializable(typeof(ZoomNet.Models.RecurrenceType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.RecurringMeeting[]))]
	[JsonSerializable(typeof(ZoomNet.Models.RecurringWebinar[]))]
	[JsonSerializable(typeof(ZoomNet.Models.Registrant[]))]
	[JsonSerializable(typeof(ZoomNet.Models.RegistrantInfo[]))]
	[JsonSerializable(typeof(ZoomNet.Models.RegistrantStatus[]))]
	[JsonSerializable(typeof(ZoomNet.Models.RegistrationAnswer[]))]
	[JsonSerializable(typeof(ZoomNet.Models.RegistrationCustomQuestionForMeeting[]))]
	[JsonSerializable(typeof(ZoomNet.Models.RegistrationCustomQuestionForWebinar[]))]
	[JsonSerializable(typeof(ZoomNet.Models.RegistrationCustomQuestionTypeForMeeting[]))]
	[JsonSerializable(typeof(ZoomNet.Models.RegistrationCustomQuestionTypeForWebinar[]))]
	[JsonSerializable(typeof(ZoomNet.Models.RegistrationField[]))]
	[JsonSerializable(typeof(ZoomNet.Models.RegistrationQuestionsForMeeting[]))]
	[JsonSerializable(typeof(ZoomNet.Models.RegistrationQuestionsForWebinar[]))]
	[JsonSerializable(typeof(ZoomNet.Models.RegistrationType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ReportHost[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ReportHostType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ReportMeetingParticipant[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ReportMeetingType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ReportParticipant[]))]
	[JsonSerializable(typeof(ZoomNet.Models.Role[]))]
	[JsonSerializable(typeof(ZoomNet.Models.RoleInPurchaseProcess[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ScheduledMeeting[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ScheduledMeetingUserSettings[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ScheduledWebinar[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ScreenshareContentType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ScreenshareDetails[]))]
	[JsonSerializable(typeof(ZoomNet.Models.SecuritySettings[]))]
	[JsonSerializable(typeof(ZoomNet.Models.SharingAndRecordingDetail[]))]
	[JsonSerializable(typeof(ZoomNet.Models.StreamingService[]))]
	[JsonSerializable(typeof(ZoomNet.Models.Survey[]))]
	[JsonSerializable(typeof(ZoomNet.Models.SurveyDetails[]))]
	[JsonSerializable(typeof(ZoomNet.Models.SurveyQuestion[]))]
	[JsonSerializable(typeof(ZoomNet.Models.SurveyQuestionType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.TelephonyRegionsSettings[]))]
	[JsonSerializable(typeof(ZoomNet.Models.TelephonyUserSettings[]))]
	[JsonSerializable(typeof(ZoomNet.Models.TimeZones[]))]
	[JsonSerializable(typeof(ZoomNet.Models.TrackingSource[]))]
	[JsonSerializable(typeof(ZoomNet.Models.TspUserSettings[]))]
	[JsonSerializable(typeof(ZoomNet.Models.User[]))]
	[JsonSerializable(typeof(ZoomNet.Models.UserCallLog[]))]
	[JsonSerializable(typeof(ZoomNet.Models.UserCreateType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.UserProfile[]))]
	[JsonSerializable(typeof(ZoomNet.Models.UserRecordingStorageSettings[]))]
	[JsonSerializable(typeof(ZoomNet.Models.UserSettings[]))]
	[JsonSerializable(typeof(ZoomNet.Models.UserStatus[]))]
	[JsonSerializable(typeof(ZoomNet.Models.UsersWhoCanAdmitParticipantsFromWaitingRoom[]))]
	[JsonSerializable(typeof(ZoomNet.Models.UserType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.VirtualBackgroundFile[]))]
	[JsonSerializable(typeof(ZoomNet.Models.VirtualBackgroundSettings[]))]
	[JsonSerializable(typeof(ZoomNet.Models.VirtualBackgroundType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.WaitingRoomSettings[]))]
	[JsonSerializable(typeof(ZoomNet.Models.WebhookParticipant[]))]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.AppDeauthorizedEvent[]), TypeInfoPropertyName = "WebhooksAppDeauthorizedEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.EndpointUrlValidationEvent[]), TypeInfoPropertyName = "WebhooksEndpointUrlValidationEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.Event[]), TypeInfoPropertyName = "WebhooksEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.EventType[]), TypeInfoPropertyName = "WebhooksEventTypeArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingCreatedEvent[]), TypeInfoPropertyName = "WebhooksMeetingCreatedEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingDeletedEvent[]), TypeInfoPropertyName = "WebhooksMeetingDeletedEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingEndedEvent[]), TypeInfoPropertyName = "WebhooksMeetingEndedEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingEvent[]), TypeInfoPropertyName = "WebhooksMeetingEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingLiveStreamStartedEvent[]), TypeInfoPropertyName = "WebhooksMeetingLiveStreamStartedEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingLiveStreamStoppedEvent[]), TypeInfoPropertyName = "WebhooksMeetingLiveStreamStoppedEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingParticipantAdmittedEvent[]), TypeInfoPropertyName = "WebhooksMeetingParticipantAdmittedEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingParticipantJoinedBeforeHostEvent[]), TypeInfoPropertyName = "WebhooksMeetingParticipantJoinedBeforeHostEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingParticipantJoinedEvent[]), TypeInfoPropertyName = "WebhooksMeetingParticipantJoinedEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingParticipantJoinedWaitingRoomEvent[]), TypeInfoPropertyName = "WebhooksMeetingParticipantJoinedWaitingRoomEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingParticipantLeftEvent[]), TypeInfoPropertyName = "WebhooksMeetingParticipantLeftEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingParticipantLeftWaitingRoomEvent[]), TypeInfoPropertyName = "WebhooksMeetingParticipantLeftWaitingRoomEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingParticipantSentToWaitingRoomEvent[]), TypeInfoPropertyName = "WebhooksMeetingParticipantSentToWaitingRoomEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingParticipantWaitingForHostEvent[]), TypeInfoPropertyName = "WebhooksMeetingParticipantWaitingForHostEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingPermanentlyDeletedEvent[]), TypeInfoPropertyName = "WebhooksMeetingPermanentlyDeletedEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingRecoveredEvent[]), TypeInfoPropertyName = "WebhooksMeetingRecoveredEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingRegistrationApprovedEvent[]), TypeInfoPropertyName = "WebhooksMeetingRegistrationApprovedEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingRegistrationCancelledEvent[]), TypeInfoPropertyName = "WebhooksMeetingRegistrationCancelledEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingRegistrationCreatedEvent[]), TypeInfoPropertyName = "WebhooksMeetingRegistrationCreatedEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingRegistrationDeniedEvent[]), TypeInfoPropertyName = "WebhooksMeetingRegistrationDeniedEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingServiceIssueEvent[]), TypeInfoPropertyName = "WebhooksMeetingServiceIssueEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingSharingEndedEvent[]), TypeInfoPropertyName = "WebhooksMeetingSharingEndedEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingSharingStartedEvent[]), TypeInfoPropertyName = "WebhooksMeetingSharingStartedEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingStartedEvent[]), TypeInfoPropertyName = "WebhooksMeetingStartedEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingUpdatedEvent[]), TypeInfoPropertyName = "WebhooksMeetingUpdatedEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.WebinarCreatedEvent[]), TypeInfoPropertyName = "WebhooksWebinarCreatedEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.WebinarDeletedEvent[]), TypeInfoPropertyName = "WebhooksWebinarDeletedEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.WebinarEndedEvent[]), TypeInfoPropertyName = "WebhooksWebinarEndedEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.WebinarEvent[]), TypeInfoPropertyName = "WebhooksWebinarEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.WebinarParticipantJoinedEvent[]), TypeInfoPropertyName = "WebhooksWebinarParticipantJoinedEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.WebinarParticipantLeftEvent[]), TypeInfoPropertyName = "WebhooksWebinarParticipantLeftEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.WebinarRegistrationApprovedEvent[]), TypeInfoPropertyName = "WebhooksWebinarRegistrationApprovedEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.WebinarRegistrationCancelledEvent[]), TypeInfoPropertyName = "WebhooksWebinarRegistrationCancelledEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.WebinarRegistrationCreatedEvent[]), TypeInfoPropertyName = "WebhooksWebinarRegistrationCreatedEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.WebinarRegistrationDeniedEvent[]), TypeInfoPropertyName = "WebhooksWebinarRegistrationDeniedEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.WebinarServiceIssueEvent[]), TypeInfoPropertyName = "WebhooksWebinarServiceIssueEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.WebinarSharingEndedEvent[]), TypeInfoPropertyName = "WebhooksWebinarSharingEndedEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.WebinarSharingStartedEvent[]), TypeInfoPropertyName = "WebhooksWebinarSharingStartedEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.WebinarStartedEvent[]), TypeInfoPropertyName = "WebhooksWebinarStartedEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.WebinarUpdatedEvent[]), TypeInfoPropertyName = "WebhooksWebinarUpdatedEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webinar[]))]
	[JsonSerializable(typeof(ZoomNet.Models.WebinarChatSettings[]))]
	[JsonSerializable(typeof(ZoomNet.Models.WebinarChatType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.WebinarLiveStreamingSettings[]))]
	[JsonSerializable(typeof(ZoomNet.Models.WebinarPollingSettings[]))]
	[JsonSerializable(typeof(ZoomNet.Models.WebinarSettings[]))]
	[JsonSerializable(typeof(ZoomNet.Models.WebinarSummary[]))]
	[JsonSerializable(typeof(ZoomNet.Models.WebinarTemplate[]))]
	[JsonSerializable(typeof(ZoomNet.Models.WebinarType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.WhoCanShare[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ZoomRoom[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ZoomRoomIssueDetails[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ZoomRoomWithIssues[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ZoomRoomWithIssuesReport[]))]

	[JsonSerializable(typeof(ZoomNet.Models.ApprovalType?))]
	[JsonSerializable(typeof(ZoomNet.Models.AttendeeChatSaveType?))]
	[JsonSerializable(typeof(ZoomNet.Models.AttendeeChatType?))]
	[JsonSerializable(typeof(ZoomNet.Models.AudioType?))]
	[JsonSerializable(typeof(ZoomNet.Models.AuthenticationType?))]
	[JsonSerializable(typeof(ZoomNet.Models.CallLogCalleeNumberType?))]
	[JsonSerializable(typeof(ZoomNet.Models.CallLogCallerNumberType?))]
	[JsonSerializable(typeof(ZoomNet.Models.CallLogCallType?))]
	[JsonSerializable(typeof(ZoomNet.Models.CallLogDirection?))]
	[JsonSerializable(typeof(ZoomNet.Models.CallLogNumberSource?))]
	[JsonSerializable(typeof(ZoomNet.Models.CallLogResult?))]
	[JsonSerializable(typeof(ZoomNet.Models.CallLogTransferInfoExtensionType?))]
	[JsonSerializable(typeof(ZoomNet.Models.CallLogTransferInfoNumberType?))]
	[JsonSerializable(typeof(ZoomNet.Models.CallLogType?))]
	[JsonSerializable(typeof(ZoomNet.Models.ChatChannelRole?))]
	[JsonSerializable(typeof(ZoomNet.Models.ChatChannelType?))]
	[JsonSerializable(typeof(ZoomNet.Models.ChatMentionType?))]
	[JsonSerializable(typeof(ZoomNet.Models.ChimeType?))]
	[JsonSerializable(typeof(ZoomNet.Models.ConcurrentMeetingType?))]
	[JsonSerializable(typeof(ZoomNet.Models.ContactType?))]
	[JsonSerializable(typeof(ZoomNet.Models.Country?))]
	[JsonSerializable(typeof(ZoomNet.Models.DashboardMeetingType?))]
	[JsonSerializable(typeof(ZoomNet.Models.DataCenterRegion?))]
	[JsonSerializable(typeof(ZoomNet.Models.EncryptionType?))]
	[JsonSerializable(typeof(ZoomNet.Models.InterpretationLanguage?))]
	[JsonSerializable(typeof(ZoomNet.Models.IssueType?))]
	[JsonSerializable(typeof(ZoomNet.Models.JoinBeforeHostTime?))]
	[JsonSerializable(typeof(ZoomNet.Models.Language?))]
	[JsonSerializable(typeof(ZoomNet.Models.LoginType?))]
	[JsonSerializable(typeof(ZoomNet.Models.MeetingListType?))]
	[JsonSerializable(typeof(ZoomNet.Models.MeetingStatus?))]
	[JsonSerializable(typeof(ZoomNet.Models.MeetingTemplateType?))]
	[JsonSerializable(typeof(ZoomNet.Models.MeetingType?))]
	[JsonSerializable(typeof(ZoomNet.Models.NumberOfEmployees?))]
	[JsonSerializable(typeof(ZoomNet.Models.OAuthGrantType?))]
	[JsonSerializable(typeof(ZoomNet.Models.ParticipantChatSaveType?))]
	[JsonSerializable(typeof(ZoomNet.Models.ParticipantChatType?))]
	[JsonSerializable(typeof(ZoomNet.Models.ParticipantDevice?))]
	[JsonSerializable(typeof(ZoomNet.Models.ParticipantNetwork?))]
	[JsonSerializable(typeof(ZoomNet.Models.ParticipantStatus?))]
	[JsonSerializable(typeof(ZoomNet.Models.ParticipantsToPlaceInWaitingRoom?))]
	[JsonSerializable(typeof(ZoomNet.Models.PayMode?))]
	[JsonSerializable(typeof(ZoomNet.Models.PhoneType?))]
	[JsonSerializable(typeof(ZoomNet.Models.PmiMeetingPasswordRequirementType?))]
	[JsonSerializable(typeof(ZoomNet.Models.PollQuestionType?))]
	[JsonSerializable(typeof(ZoomNet.Models.PollStatus?))]
	[JsonSerializable(typeof(ZoomNet.Models.PollType?))]
	[JsonSerializable(typeof(ZoomNet.Models.PresenceStatus?))]
	[JsonSerializable(typeof(ZoomNet.Models.PronounDisplayType?))]
	[JsonSerializable(typeof(ZoomNet.Models.PurchasingTimeFrame?))]
	[JsonSerializable(typeof(ZoomNet.Models.QualityType?))]
	[JsonSerializable(typeof(ZoomNet.Models.RecordingContentType?))]
	[JsonSerializable(typeof(ZoomNet.Models.RecordingFileType?))]
	[JsonSerializable(typeof(ZoomNet.Models.RecordingSharingType?))]
	[JsonSerializable(typeof(ZoomNet.Models.RecordingType?))]
	[JsonSerializable(typeof(ZoomNet.Models.RecurrenceType?))]
	[JsonSerializable(typeof(ZoomNet.Models.RegistrantStatus?))]
	[JsonSerializable(typeof(ZoomNet.Models.RegistrationCustomQuestionTypeForMeeting?))]
	[JsonSerializable(typeof(ZoomNet.Models.RegistrationCustomQuestionTypeForWebinar?))]
	[JsonSerializable(typeof(ZoomNet.Models.RegistrationField?))]
	[JsonSerializable(typeof(ZoomNet.Models.RegistrationType?))]
	[JsonSerializable(typeof(ZoomNet.Models.ReportHostType?))]
	[JsonSerializable(typeof(ZoomNet.Models.ReportMeetingType?))]
	[JsonSerializable(typeof(ZoomNet.Models.RoleInPurchaseProcess?))]
	[JsonSerializable(typeof(ZoomNet.Models.ScreenshareContentType?))]
	[JsonSerializable(typeof(ZoomNet.Models.StreamingService?))]
	[JsonSerializable(typeof(ZoomNet.Models.SurveyQuestionType?))]
	[JsonSerializable(typeof(ZoomNet.Models.TimeZones?))]
	[JsonSerializable(typeof(ZoomNet.Models.UserCreateType?))]
	[JsonSerializable(typeof(ZoomNet.Models.UserStatus?))]
	[JsonSerializable(typeof(ZoomNet.Models.UsersWhoCanAdmitParticipantsFromWaitingRoom?))]
	[JsonSerializable(typeof(ZoomNet.Models.UserType?))]
	[JsonSerializable(typeof(ZoomNet.Models.VirtualBackgroundType?))]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.EventType?), TypeInfoPropertyName = "WebhooksEventTypeNullable")]
	[JsonSerializable(typeof(ZoomNet.Models.WebinarChatType?))]
	[JsonSerializable(typeof(ZoomNet.Models.WebinarType?))]
	[JsonSerializable(typeof(ZoomNet.Models.WhoCanShare?))]
	internal partial class ZoomNetJsonSerializerContext : JsonSerializerContext
	{
	}
}
