using System.Text.Json.Serialization;

namespace ZoomNet.Json
{
	[JsonSerializable(typeof(System.Text.Json.Nodes.JsonObject))]
	[JsonSerializable(typeof(System.Text.Json.Nodes.JsonObject[]))]

	[JsonSerializable(typeof(ZoomNet.Models.Account))]
	[JsonSerializable(typeof(ZoomNet.Models.AccountCallLog))]
	[JsonSerializable(typeof(ZoomNet.Models.ApprovalType))]
	[JsonSerializable(typeof(ZoomNet.Models.Assistant))]
	[JsonSerializable(typeof(ZoomNet.Models.AttendeeChatSaveType))]
	[JsonSerializable(typeof(ZoomNet.Models.AttendeeChatType))]
	[JsonSerializable(typeof(ZoomNet.Models.AudioConferencingCallSettings))]
	[JsonSerializable(typeof(ZoomNet.Models.AudioConferencingPhoneNumberInformation))]
	[JsonSerializable(typeof(ZoomNet.Models.AudioConferencingUserSettings))]
	[JsonSerializable(typeof(ZoomNet.Models.AudioType))]
	[JsonSerializable(typeof(ZoomNet.Models.AuthenticationOptions))]
	[JsonSerializable(typeof(ZoomNet.Models.AuthenticationSettings))]
	[JsonSerializable(typeof(ZoomNet.Models.AuthenticationType))]
	[JsonSerializable(typeof(ZoomNet.Models.AutoRecordingType))]
	[JsonSerializable(typeof(ZoomNet.Models.BatchRegistrant))]
	[JsonSerializable(typeof(ZoomNet.Models.BatchRegistrantInfo))]
	[JsonSerializable(typeof(ZoomNet.Models.BillingBasePlanUsage))]
	[JsonSerializable(typeof(ZoomNet.Models.BillingEmployeeCount))]
	[JsonSerializable(typeof(ZoomNet.Models.BillingInfo))]
	[JsonSerializable(typeof(ZoomNet.Models.BillingInvoiceDetails))]
	[JsonSerializable(typeof(ZoomNet.Models.BillingInvoiceItem))]
	[JsonSerializable(typeof(ZoomNet.Models.BillingInvoiceSummary))]
	[JsonSerializable(typeof(ZoomNet.Models.BillingPlanUsage))]
	[JsonSerializable(typeof(ZoomNet.Models.BillingPlanUsageInfo))]
	[JsonSerializable(typeof(ZoomNet.Models.BillingRecordingPlanUsage))]
	[JsonSerializable(typeof(ZoomNet.Models.BillingUnitedPlanUsage))]
	[JsonSerializable(typeof(ZoomNet.Models.CalendarIntegrationType))]
	[JsonSerializable(typeof(ZoomNet.Models.CallHandlingSettings.BusyOnAnotherCallActionType), TypeInfoPropertyName = "CallHandlingSettingsBusyOnAnotherCallActionType")]
	[JsonSerializable(typeof(ZoomNet.Models.CallHandlingSettings.CallDistributionSettings), TypeInfoPropertyName = "CallHandlingSettingsCallDistributionSettings")]
	[JsonSerializable(typeof(ZoomNet.Models.CallHandlingSettings.CallForwardingChildSubsettings), TypeInfoPropertyName = "CallHandlingSettingsCallForwardingChildSubsettings")]
	[JsonSerializable(typeof(ZoomNet.Models.CallHandlingSettings.CallForwardingSubsettings), TypeInfoPropertyName = "CallHandlingSettingsCallForwardingSubsettings")]
	[JsonSerializable(typeof(ZoomNet.Models.CallHandlingSettings.CallHandlingSettingType), TypeInfoPropertyName = "CallHandlingSettingsCallHandlingSettingType")]
	[JsonSerializable(typeof(ZoomNet.Models.CallHandlingSettings.CallHandlingSubsettings), TypeInfoPropertyName = "CallHandlingSettingsCallHandlingSubsettings")]
	[JsonSerializable(typeof(ZoomNet.Models.CallHandlingSettings.CallHandlingSubsettingsBase), TypeInfoPropertyName = "CallHandlingSettingsCallHandlingSubsettingsBase")]
	[JsonSerializable(typeof(ZoomNet.Models.CallHandlingSettings.CallHandlingSubsettingsType), TypeInfoPropertyName = "CallHandlingSettingsCallHandlingSubsettingsType")]
	[JsonSerializable(typeof(ZoomNet.Models.CallHandlingSettings.CallNotAnswerActionType), TypeInfoPropertyName = "CallHandlingSettingsCallNotAnswerActionType")]
	[JsonSerializable(typeof(ZoomNet.Models.CallHandlingSettings.CustomHoursChildSubsettings), TypeInfoPropertyName = "CallHandlingSettingsCustomHoursChildSubsettings")]
	[JsonSerializable(typeof(ZoomNet.Models.CallHandlingSettings.CustomHoursSubsettings), TypeInfoPropertyName = "CallHandlingSettingsCustomHoursSubsettings")]
	[JsonSerializable(typeof(ZoomNet.Models.CallHandlingSettings.CustomHoursType), TypeInfoPropertyName = "CallHandlingSettingsCustomHoursType")]
	[JsonSerializable(typeof(ZoomNet.Models.CallHandlingSettings.HolidaySubsettings), TypeInfoPropertyName = "CallHandlingSettingsHolidaySubsettings")]
	[JsonSerializable(typeof(ZoomNet.Models.CallHandlingSettings.RingModeType), TypeInfoPropertyName = "CallHandlingSettingsRingModeType")]
	[JsonSerializable(typeof(ZoomNet.Models.CallingPlan))]
	[JsonSerializable(typeof(ZoomNet.Models.CallingPlanType))]
	[JsonSerializable(typeof(ZoomNet.Models.CallLog))]
	[JsonSerializable(typeof(ZoomNet.Models.CallLogCalleeNumberType))]
	[JsonSerializable(typeof(ZoomNet.Models.CallLogCallerNumberType))]
	[JsonSerializable(typeof(ZoomNet.Models.CallLogCallType))]
	[JsonSerializable(typeof(ZoomNet.Models.CallLogDirection))]
	[JsonSerializable(typeof(ZoomNet.Models.CallLogNumberSource))]
	[JsonSerializable(typeof(ZoomNet.Models.CallLogOwnerInfo))]
	[JsonSerializable(typeof(ZoomNet.Models.CallLogOwnerType))]
	[JsonSerializable(typeof(ZoomNet.Models.CallLogPathType))]
	[JsonSerializable(typeof(ZoomNet.Models.CallLogResult))]
	[JsonSerializable(typeof(ZoomNet.Models.CallLogSite))]
	[JsonSerializable(typeof(ZoomNet.Models.CallLogTimeType))]
	[JsonSerializable(typeof(ZoomNet.Models.CallLogTransferInfo))]
	[JsonSerializable(typeof(ZoomNet.Models.CallLogTransferInfoExtensionType))]
	[JsonSerializable(typeof(ZoomNet.Models.CallLogTransferInfoNumberType))]
	[JsonSerializable(typeof(ZoomNet.Models.CallLogType))]
	[JsonSerializable(typeof(ZoomNet.Models.ChatbotMessage.ChatbotAction), TypeInfoPropertyName = "ChatbotMessageChatbotAction")]
	[JsonSerializable(typeof(ZoomNet.Models.ChatbotMessage.ChatbotActions), TypeInfoPropertyName = "ChatbotMessageChatbotActions")]
	[JsonSerializable(typeof(ZoomNet.Models.ChatbotMessage.ChatbotActionStyle), TypeInfoPropertyName = "ChatbotMessageChatbotActionStyle")]
	[JsonSerializable(typeof(ZoomNet.Models.ChatbotMessage.ChatbotAttachment), TypeInfoPropertyName = "ChatbotMessageChatbotAttachment")]
	[JsonSerializable(typeof(ZoomNet.Models.ChatbotMessage.ChatbotAttachmentInformation), TypeInfoPropertyName = "ChatbotMessageChatbotAttachmentInformation")]
	[JsonSerializable(typeof(ZoomNet.Models.ChatbotMessage.ChatbotContent), TypeInfoPropertyName = "ChatbotMessageChatbotContent")]
	[JsonSerializable(typeof(ZoomNet.Models.ChatbotMessage.ChatbotDropdownItem), TypeInfoPropertyName = "ChatbotMessageChatbotDropdownItem")]
	[JsonSerializable(typeof(ZoomNet.Models.ChatbotMessage.ChatbotDropdownList), TypeInfoPropertyName = "ChatbotMessageChatbotDropdownList")]
	[JsonSerializable(typeof(ZoomNet.Models.ChatbotMessage.ChatbotDropdownStaticSource), TypeInfoPropertyName = "ChatbotMessageChatbotDropdownStaticSource")]
	[JsonSerializable(typeof(ZoomNet.Models.ChatbotMessage.ChatbotFormField), TypeInfoPropertyName = "ChatbotMessageChatbotFormField")]
	[JsonSerializable(typeof(ZoomNet.Models.ChatbotMessage.ChatbotFormFields), TypeInfoPropertyName = "ChatbotMessageChatbotFormFields")]
	[JsonSerializable(typeof(ZoomNet.Models.ChatbotMessage.ChatbotHeader), TypeInfoPropertyName = "ChatbotMessageChatbotHeader")]
	[JsonSerializable(typeof(ZoomNet.Models.ChatbotMessage.ChatbotMessageLine), TypeInfoPropertyName = "ChatbotMessageChatbotMessageLine")]
	[JsonSerializable(typeof(ZoomNet.Models.ChatbotMessage.ChatbotMessageStyle), TypeInfoPropertyName = "ChatbotMessageChatbotMessageStyle")]
	[JsonSerializable(typeof(ZoomNet.Models.ChatbotMessage.ChatbotMessageText), TypeInfoPropertyName = "ChatbotMessageChatbotMessageText")]
	[JsonSerializable(typeof(ZoomNet.Models.ChatbotMessage.ChatbotSection), TypeInfoPropertyName = "ChatbotMessageChatbotSection")]
	[JsonSerializable(typeof(ZoomNet.Models.ChatbotMessageInformation))]
	[JsonSerializable(typeof(ZoomNet.Models.ChatChannel))]
	[JsonSerializable(typeof(ZoomNet.Models.ChatChannelAddMemberPermissions))]
	[JsonSerializable(typeof(ZoomNet.Models.ChatChannelMember))]
	[JsonSerializable(typeof(ZoomNet.Models.ChatChannelMentionAllPermissions))]
	[JsonSerializable(typeof(ZoomNet.Models.ChatChannelPostingPermissions))]
	[JsonSerializable(typeof(ZoomNet.Models.ChatChannelRole))]
	[JsonSerializable(typeof(ZoomNet.Models.ChatChannelSettings))]
	[JsonSerializable(typeof(ZoomNet.Models.ChatChannelType))]
	[JsonSerializable(typeof(ZoomNet.Models.ChatMembersEditResult))]
	[JsonSerializable(typeof(ZoomNet.Models.ChatMention))]
	[JsonSerializable(typeof(ZoomNet.Models.ChatMentionType))]
	[JsonSerializable(typeof(ZoomNet.Models.ChatMessage))]
	[JsonSerializable(typeof(ZoomNet.Models.ChimeType))]
	[JsonSerializable(typeof(ZoomNet.Models.ClientFeedbackDetail))]
	[JsonSerializable(typeof(ZoomNet.Models.ClientFeedbackMetrics))]
	[JsonSerializable(typeof(ZoomNet.Models.ClientFeedbackMetricsReport))]
	[JsonSerializable(typeof(ZoomNet.Models.ClientSatisfactionMetrics))]
	[JsonSerializable(typeof(ZoomNet.Models.ClientSatisfactionReport))]
	[JsonSerializable(typeof(ZoomNet.Models.ClosedCaptioningSettings))]
	[JsonSerializable(typeof(ZoomNet.Models.ConcurrentMeetingType))]
	[JsonSerializable(typeof(ZoomNet.Models.Contact))]
	[JsonSerializable(typeof(ZoomNet.Models.ContactType))]
	[JsonSerializable(typeof(ZoomNet.Models.ContinuousMeetingChatSettings))]
	[JsonSerializable(typeof(ZoomNet.Models.Country))]
	[JsonSerializable(typeof(ZoomNet.Models.CrcPortMetrics))]
	[JsonSerializable(typeof(ZoomNet.Models.CrcPortsHourUsage))]
	[JsonSerializable(typeof(ZoomNet.Models.CrcPortsUsage))]
	[JsonSerializable(typeof(ZoomNet.Models.CustomAttribute))]
	[JsonSerializable(typeof(ZoomNet.Models.DailyUsageReport))]
	[JsonSerializable(typeof(ZoomNet.Models.DailyUsageSummary))]
	[JsonSerializable(typeof(ZoomNet.Models.DashboardMeetingMetrics))]
	[JsonSerializable(typeof(ZoomNet.Models.DashboardMeetingMetricsPaginationObject))]
	[JsonSerializable(typeof(ZoomNet.Models.DashboardMeetingParticipant))]
	[JsonSerializable(typeof(ZoomNet.Models.DashboardMeetingParticipantQos))]
	[JsonSerializable(typeof(ZoomNet.Models.DashboardMeetingType))]
	[JsonSerializable(typeof(ZoomNet.Models.DashboardMetricsBase))]
	[JsonSerializable(typeof(ZoomNet.Models.DashboardParticipant))]
	[JsonSerializable(typeof(ZoomNet.Models.DashboardParticipantQos))]
	[JsonSerializable(typeof(ZoomNet.Models.DataCenterRegion))]
	[JsonSerializable(typeof(ZoomNet.Models.EmailNotificationUserSettings))]
	[JsonSerializable(typeof(ZoomNet.Models.EmergencyAddress))]
	[JsonSerializable(typeof(ZoomNet.Models.EncryptionType))]
	[JsonSerializable(typeof(ZoomNet.Models.ExternalContact))]
	[JsonSerializable(typeof(ZoomNet.Models.ExternalContactDetails))]
	[JsonSerializable(typeof(ZoomNet.Models.FeatureUserSettings))]
	[JsonSerializable(typeof(ZoomNet.Models.Group))]
	[JsonSerializable(typeof(ZoomNet.Models.GroupAdministrator))]
	[JsonSerializable(typeof(ZoomNet.Models.GroupMember))]
	[JsonSerializable(typeof(ZoomNet.Models.GroupMemberType))]
	[JsonSerializable(typeof(ZoomNet.Models.ImMetric))]
	[JsonSerializable(typeof(ZoomNet.Models.InstantMeeting))]
	[JsonSerializable(typeof(ZoomNet.Models.InstantMeetingUserSettings))]
	[JsonSerializable(typeof(ZoomNet.Models.InterpretationLanguage))]
	[JsonSerializable(typeof(ZoomNet.Models.InviteLink))]
	[JsonSerializable(typeof(ZoomNet.Models.IpAddressAccessControlSettings))]
	[JsonSerializable(typeof(ZoomNet.Models.IssuesOfZoomRooms))]
	[JsonSerializable(typeof(ZoomNet.Models.IssuesOfZoomRoomsReport))]
	[JsonSerializable(typeof(ZoomNet.Models.IssueType))]
	[JsonSerializable(typeof(ZoomNet.Models.JoinBeforeHostTime))]
	[JsonSerializable(typeof(ZoomNet.Models.Language))]
	[JsonSerializable(typeof(ZoomNet.Models.LanguageInterpretationSettings))]
	[JsonSerializable(typeof(ZoomNet.Models.LiveStreamingInfo))]
	[JsonSerializable(typeof(ZoomNet.Models.LiveStreamingSettings))]
	[JsonSerializable(typeof(ZoomNet.Models.LoginType))]
	[JsonSerializable(typeof(ZoomNet.Models.ManualCaptioningSettings))]
	[JsonSerializable(typeof(ZoomNet.Models.Meeting))]
	[JsonSerializable(typeof(ZoomNet.Models.MeetingFile))]
	[JsonSerializable(typeof(ZoomNet.Models.MeetingListType))]
	[JsonSerializable(typeof(ZoomNet.Models.MeetingOccurrence))]
	[JsonSerializable(typeof(ZoomNet.Models.MeetingSettings))]
	[JsonSerializable(typeof(ZoomNet.Models.MeetingStatus))]
	[JsonSerializable(typeof(ZoomNet.Models.MeetingSummary))]
	[JsonSerializable(typeof(ZoomNet.Models.MeetingTemplate))]
	[JsonSerializable(typeof(ZoomNet.Models.MeetingTemplateType))]
	[JsonSerializable(typeof(ZoomNet.Models.MeetingType))]
	[JsonSerializable(typeof(ZoomNet.Models.NumberOfEmployees))]
	[JsonSerializable(typeof(ZoomNet.Models.OAuthGrantType))]
	[JsonSerializable(typeof(ZoomNet.Models.Panelist))]
	[JsonSerializable(typeof(ZoomNet.Models.Participant))]
	[JsonSerializable(typeof(ZoomNet.Models.ParticipantChatSaveType))]
	[JsonSerializable(typeof(ZoomNet.Models.ParticipantChatType))]
	[JsonSerializable(typeof(ZoomNet.Models.ParticipantDevice))]
	[JsonSerializable(typeof(ZoomNet.Models.ParticipantNetwork))]
	[JsonSerializable(typeof(ZoomNet.Models.ParticipantSharingDetails))]
	[JsonSerializable(typeof(ZoomNet.Models.ParticipantStatus))]
	[JsonSerializable(typeof(ZoomNet.Models.ParticipantsToPlaceInWaitingRoom))]
	[JsonSerializable(typeof(ZoomNet.Models.PasswordRequirements))]
	[JsonSerializable(typeof(ZoomNet.Models.PastInstance))]
	[JsonSerializable(typeof(ZoomNet.Models.PastMeeting))]
	[JsonSerializable(typeof(ZoomNet.Models.PayMode))]
	[JsonSerializable(typeof(ZoomNet.Models.PhoneCallPhoneNumber))]
	[JsonSerializable(typeof(ZoomNet.Models.PhoneCallRecording))]
	[JsonSerializable(typeof(ZoomNet.Models.PhoneCallRecordingCalleeNumberType))]
	[JsonSerializable(typeof(ZoomNet.Models.PhoneCallRecordingCallerNumberType))]
	[JsonSerializable(typeof(ZoomNet.Models.PhoneCallRecordingDisclaimerStatus))]
	[JsonSerializable(typeof(ZoomNet.Models.PhoneCallRecordingOwner))]
	[JsonSerializable(typeof(ZoomNet.Models.PhoneCallRecordingOwnerExtensionStatus))]
	[JsonSerializable(typeof(ZoomNet.Models.PhoneCallRecordingOwnerType))]
	[JsonSerializable(typeof(ZoomNet.Models.PhoneCallRecordingTranscript))]
	[JsonSerializable(typeof(ZoomNet.Models.PhoneCallRecordingTranscriptTimelineFraction))]
	[JsonSerializable(typeof(ZoomNet.Models.PhoneCallRecordingTranscriptTimelineUser))]
	[JsonSerializable(typeof(ZoomNet.Models.PhoneCallRecordingType))]
	[JsonSerializable(typeof(ZoomNet.Models.PhoneCallUser))]
	[JsonSerializable(typeof(ZoomNet.Models.PhoneCallUserProfile))]
	[JsonSerializable(typeof(ZoomNet.Models.PhoneCallUserStatus))]
	[JsonSerializable(typeof(ZoomNet.Models.PhoneNumber))]
	[JsonSerializable(typeof(ZoomNet.Models.PhoneType))]
	[JsonSerializable(typeof(ZoomNet.Models.PhoneUser))]
	[JsonSerializable(typeof(ZoomNet.Models.PhoneDetail))]
	[JsonSerializable(typeof(ZoomNet.Models.PmiMeetingPasswordRequirementType))]
	[JsonSerializable(typeof(ZoomNet.Models.Poll))]
	[JsonSerializable(typeof(ZoomNet.Models.PollAnswer))]
	[JsonSerializable(typeof(ZoomNet.Models.PollPrompt))]
	[JsonSerializable(typeof(ZoomNet.Models.PollQuestion))]
	[JsonSerializable(typeof(ZoomNet.Models.PollQuestionType))]
	[JsonSerializable(typeof(ZoomNet.Models.PollResult))]
	[JsonSerializable(typeof(ZoomNet.Models.PollStatus))]
	[JsonSerializable(typeof(ZoomNet.Models.PollType))]
	[JsonSerializable(typeof(ZoomNet.Models.PresenceStatus))]
	[JsonSerializable(typeof(ZoomNet.Models.PresenceStatusResponse))]
	[JsonSerializable(typeof(ZoomNet.Models.PronounDisplayType))]
	[JsonSerializable(typeof(ZoomNet.Models.PurchasingTimeFrame))]
	[JsonSerializable(typeof(ZoomNet.Models.QualityOfService.CpuUsage), TypeInfoPropertyName = "QualityOfServiceCpuUsage")]
	[JsonSerializable(typeof(ZoomNet.Models.QualityOfService.PacketQualityOfServiceMetrics), TypeInfoPropertyName = "QualityOfServicePacketQualityOfServiceMetrics")]
	[JsonSerializable(typeof(ZoomNet.Models.QualityOfService.VideoQualityOfServiceMetrics), TypeInfoPropertyName = "QualityOfServiceVideoQualityOfServiceMetrics")]
	[JsonSerializable(typeof(ZoomNet.Models.QualityType))]
	[JsonSerializable(typeof(ZoomNet.Models.Recording))]
	[JsonSerializable(typeof(ZoomNet.Models.RecordingContentType))]
	[JsonSerializable(typeof(ZoomNet.Models.RecordingFile))]
	[JsonSerializable(typeof(ZoomNet.Models.RecordingFileExtension))]
	[JsonSerializable(typeof(ZoomNet.Models.RecordingFileType))]
	[JsonSerializable(typeof(ZoomNet.Models.RecordingRegistration))]
	[JsonSerializable(typeof(ZoomNet.Models.RecordingSettings))]
	[JsonSerializable(typeof(ZoomNet.Models.RecordingSharingType))]
	[JsonSerializable(typeof(ZoomNet.Models.RecordingStatus))]
	[JsonSerializable(typeof(ZoomNet.Models.RecordingType))]
	[JsonSerializable(typeof(ZoomNet.Models.RecordingUserSettings))]
	[JsonSerializable(typeof(ZoomNet.Models.RecurrenceInfo))]
	[JsonSerializable(typeof(ZoomNet.Models.RecurrenceType))]
	[JsonSerializable(typeof(ZoomNet.Models.RecurringMeeting))]
	[JsonSerializable(typeof(ZoomNet.Models.RecurringWebinar))]
	[JsonSerializable(typeof(ZoomNet.Models.Registrant))]
	[JsonSerializable(typeof(ZoomNet.Models.RegistrantInfo))]
	[JsonSerializable(typeof(ZoomNet.Models.RegistrantStatus))]
	[JsonSerializable(typeof(ZoomNet.Models.RegistrationAnswer))]
	[JsonSerializable(typeof(ZoomNet.Models.RegistrationCustomQuestionForMeeting))]
	[JsonSerializable(typeof(ZoomNet.Models.RegistrationCustomQuestionForWebinar))]
	[JsonSerializable(typeof(ZoomNet.Models.RegistrationCustomQuestionTypeForMeeting))]
	[JsonSerializable(typeof(ZoomNet.Models.RegistrationCustomQuestionTypeForWebinar))]
	[JsonSerializable(typeof(ZoomNet.Models.RegistrationField))]
	[JsonSerializable(typeof(ZoomNet.Models.RegistrationQuestionsForMeeting))]
	[JsonSerializable(typeof(ZoomNet.Models.RegistrationQuestionsForWebinar))]
	[JsonSerializable(typeof(ZoomNet.Models.RegistrationType))]
	[JsonSerializable(typeof(ZoomNet.Models.ReportHost))]
	[JsonSerializable(typeof(ZoomNet.Models.ReportHostType))]
	[JsonSerializable(typeof(ZoomNet.Models.ReportMeetingType))]
	[JsonSerializable(typeof(ZoomNet.Models.ReportParticipant))]
	[JsonSerializable(typeof(ZoomNet.Models.Role))]
	[JsonSerializable(typeof(ZoomNet.Models.RoleInPurchaseProcess))]
	[JsonSerializable(typeof(ZoomNet.Models.Room))]
	[JsonSerializable(typeof(ZoomNet.Models.RoomLocation))]
	[JsonSerializable(typeof(ZoomNet.Models.RoomLocationAlertSettings))]
	[JsonSerializable(typeof(ZoomNet.Models.RoomLocationBackgroundImageInfo))]
	[JsonSerializable(typeof(ZoomNet.Models.RoomLocationBasicProfile))]
	[JsonSerializable(typeof(ZoomNet.Models.RoomLocationIncomingMeetingRequestSettings))]
	[JsonSerializable(typeof(ZoomNet.Models.RoomLocationNotificationSettings))]
	[JsonSerializable(typeof(ZoomNet.Models.RoomLocationReserveOtherRoomsSettings))]
	[JsonSerializable(typeof(ZoomNet.Models.RoomLocationSchedulingDisplaySettings))]
	[JsonSerializable(typeof(ZoomNet.Models.RoomLocationSecuritySettings))]
	[JsonSerializable(typeof(ZoomNet.Models.RoomLocationSettings))]
	[JsonSerializable(typeof(ZoomNet.Models.RoomLocationSettingsType))]
	[JsonSerializable(typeof(ZoomNet.Models.RoomLocationSetupProfile))]
	[JsonSerializable(typeof(ZoomNet.Models.RoomLocationSignageSettings))]
	[JsonSerializable(typeof(ZoomNet.Models.RoomLocationType))]
	[JsonSerializable(typeof(ZoomNet.Models.RoomTag))]
	[JsonSerializable(typeof(ZoomNet.Models.RoomType))]
	[JsonSerializable(typeof(ZoomNet.Models.ScheduledMeeting))]
	[JsonSerializable(typeof(ZoomNet.Models.ScheduledMeetingUserSettings))]
	[JsonSerializable(typeof(ZoomNet.Models.ScheduledWebinar))]
	[JsonSerializable(typeof(ZoomNet.Models.ScreenshareContentType))]
	[JsonSerializable(typeof(ZoomNet.Models.ScreenshareDetails))]
	[JsonSerializable(typeof(ZoomNet.Models.SecuritySettings))]
	[JsonSerializable(typeof(ZoomNet.Models.SharingAndRecordingDetail))]
	[JsonSerializable(typeof(ZoomNet.Models.SignageBannerDisplayPeriod))]
	[JsonSerializable(typeof(ZoomNet.Models.SignageBannerSettings))]
	[JsonSerializable(typeof(ZoomNet.Models.SignageContentItem))]
	[JsonSerializable(typeof(ZoomNet.Models.SignageContentList))]
	[JsonSerializable(typeof(ZoomNet.Models.SignageLayout))]
	[JsonSerializable(typeof(ZoomNet.Models.Site))]
	[JsonSerializable(typeof(ZoomNet.Models.SmsAttachment))]
	[JsonSerializable(typeof(ZoomNet.Models.SmsAttachmentType))]
	[JsonSerializable(typeof(ZoomNet.Models.SmsDirection))]
	[JsonSerializable(typeof(ZoomNet.Models.SmsHistoryParticipant))]
	[JsonSerializable(typeof(ZoomNet.Models.SmsMessage))]
	[JsonSerializable(typeof(ZoomNet.Models.SmsMessageType))]
	[JsonSerializable(typeof(ZoomNet.Models.SmsParticipantOwner))]
	[JsonSerializable(typeof(ZoomNet.Models.SmsParticipantOwnerType))]
	[JsonSerializable(typeof(ZoomNet.Models.StreamingService))]
	[JsonSerializable(typeof(ZoomNet.Models.Survey))]
	[JsonSerializable(typeof(ZoomNet.Models.SurveyDetails))]
	[JsonSerializable(typeof(ZoomNet.Models.SurveyQuestion))]
	[JsonSerializable(typeof(ZoomNet.Models.SurveyQuestionType))]
	[JsonSerializable(typeof(ZoomNet.Models.TelephonyRegionsSettings))]
	[JsonSerializable(typeof(ZoomNet.Models.TelephonyUserSettings))]
	[JsonSerializable(typeof(ZoomNet.Models.TimeZones))]
	[JsonSerializable(typeof(ZoomNet.Models.TrackingField))]
	[JsonSerializable(typeof(ZoomNet.Models.TrackingSource))]
	[JsonSerializable(typeof(ZoomNet.Models.TspUserSettings))]
	[JsonSerializable(typeof(ZoomNet.Models.User))]
	[JsonSerializable(typeof(ZoomNet.Models.UserCallLog))]
	[JsonSerializable(typeof(ZoomNet.Models.UserCreateType))]
	[JsonSerializable(typeof(ZoomNet.Models.UserProfile))]
	[JsonSerializable(typeof(ZoomNet.Models.UserRecordingStorageSettings))]
	[JsonSerializable(typeof(ZoomNet.Models.UserSettings))]
	[JsonSerializable(typeof(ZoomNet.Models.UserStatus))]
	[JsonSerializable(typeof(ZoomNet.Models.UsersWhoCanAdmitParticipantsFromWaitingRoom))]
	[JsonSerializable(typeof(ZoomNet.Models.UserType))]
	[JsonSerializable(typeof(ZoomNet.Models.VirtualBackgroundFile))]
	[JsonSerializable(typeof(ZoomNet.Models.VirtualBackgroundSettings))]
	[JsonSerializable(typeof(ZoomNet.Models.VirtualBackgroundType))]
	[JsonSerializable(typeof(ZoomNet.Models.WaitingRoomSettings))]
	[JsonSerializable(typeof(ZoomNet.Models.WebhookParticipant))]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.AppDeauthorizedEvent), TypeInfoPropertyName = "WebhooksAppDeauthorizedEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.EndpointUrlValidationEvent), TypeInfoPropertyName = "WebhooksEndpointUrlValidationEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.Event), TypeInfoPropertyName = "WebhooksEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.EventType), TypeInfoPropertyName = "WebhooksEventType")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingCreatedEvent), TypeInfoPropertyName = "WebhooksMeetingCreatedEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingDeletedEvent), TypeInfoPropertyName = "WebhooksMeetingDeletedEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingEndedEvent), TypeInfoPropertyName = "WebhooksMeetingEndedEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingEvent), TypeInfoPropertyName = "WebhooksMeetingEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingLiveStreamStartedEvent), TypeInfoPropertyName = "WebhooksMeetingLiveStreamStartedEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingLiveStreamStoppedEvent), TypeInfoPropertyName = "WebhooksMeetingLiveStreamStoppedEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingParticipantAdmittedEvent), TypeInfoPropertyName = "WebhooksMeetingParticipantAdmittedEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingParticipantJoinedBeforeHostEvent), TypeInfoPropertyName = "WebhooksMeetingParticipantJoinedBeforeHostEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingParticipantJoinedEvent), TypeInfoPropertyName = "WebhooksMeetingParticipantJoinedEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingParticipantJoinedWaitingRoomEvent), TypeInfoPropertyName = "WebhooksMeetingParticipantJoinedWaitingRoomEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingParticipantLeftEvent), TypeInfoPropertyName = "WebhooksMeetingParticipantLeftEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingParticipantLeftWaitingRoomEvent), TypeInfoPropertyName = "WebhooksMeetingParticipantLeftWaitingRoomEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingParticipantSentToWaitingRoomEvent), TypeInfoPropertyName = "WebhooksMeetingParticipantSentToWaitingRoomEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingParticipantWaitingForHostEvent), TypeInfoPropertyName = "WebhooksMeetingParticipantWaitingForHostEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingPermanentlyDeletedEvent), TypeInfoPropertyName = "WebhooksMeetingPermanentlyDeletedEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingRecoveredEvent), TypeInfoPropertyName = "WebhooksMeetingRecoveredEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingRegistrationApprovedEvent), TypeInfoPropertyName = "WebhooksMeetingRegistrationApprovedEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingRegistrationCancelledEvent), TypeInfoPropertyName = "WebhooksMeetingRegistrationCancelledEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingRegistrationCreatedEvent), TypeInfoPropertyName = "WebhooksMeetingRegistrationCreatedEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingRegistrationDeniedEvent), TypeInfoPropertyName = "WebhooksMeetingRegistrationDeniedEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingServiceIssueEvent), TypeInfoPropertyName = "WebhooksMeetingServiceIssueEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingSharingEndedEvent), TypeInfoPropertyName = "WebhooksMeetingSharingEndedEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingSharingStartedEvent), TypeInfoPropertyName = "WebhooksMeetingSharingStartedEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingStartedEvent), TypeInfoPropertyName = "WebhooksMeetingStartedEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingUpdatedEvent), TypeInfoPropertyName = "WebhooksMeetingUpdatedEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.RecordingCompletedEvent), TypeInfoPropertyName = "WebhooksRecordingCompletedEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.RecordingEvent), TypeInfoPropertyName = "WebhooksRecordingEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.WebinarCreatedEvent), TypeInfoPropertyName = "WebhooksWebinarCreatedEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.WebinarDeletedEvent), TypeInfoPropertyName = "WebhooksWebinarDeletedEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.WebinarEndedEvent), TypeInfoPropertyName = "WebhooksWebinarEndedEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.WebinarEvent), TypeInfoPropertyName = "WebhooksWebinarEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.WebinarParticipantJoinedEvent), TypeInfoPropertyName = "WebhooksWebinarParticipantJoinedEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.WebinarParticipantLeftEvent), TypeInfoPropertyName = "WebhooksWebinarParticipantLeftEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.WebinarRegistrationApprovedEvent), TypeInfoPropertyName = "WebhooksWebinarRegistrationApprovedEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.WebinarRegistrationCancelledEvent), TypeInfoPropertyName = "WebhooksWebinarRegistrationCancelledEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.WebinarRegistrationCreatedEvent), TypeInfoPropertyName = "WebhooksWebinarRegistrationCreatedEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.WebinarRegistrationDeniedEvent), TypeInfoPropertyName = "WebhooksWebinarRegistrationDeniedEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.WebinarServiceIssueEvent), TypeInfoPropertyName = "WebhooksWebinarServiceIssueEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.WebinarSharingEndedEvent), TypeInfoPropertyName = "WebhooksWebinarSharingEndedEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.WebinarSharingStartedEvent), TypeInfoPropertyName = "WebhooksWebinarSharingStartedEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.WebinarStartedEvent), TypeInfoPropertyName = "WebhooksWebinarStartedEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.WebinarUpdatedEvent), TypeInfoPropertyName = "WebhooksWebinarUpdatedEvent")]
	[JsonSerializable(typeof(ZoomNet.Models.Webinar))]
	[JsonSerializable(typeof(ZoomNet.Models.WebinarChatSettings))]
	[JsonSerializable(typeof(ZoomNet.Models.WebinarChatType))]
	[JsonSerializable(typeof(ZoomNet.Models.WebinarLiveStreamingSettings))]
	[JsonSerializable(typeof(ZoomNet.Models.WebinarPollingSettings))]
	[JsonSerializable(typeof(ZoomNet.Models.WebinarSettings))]
	[JsonSerializable(typeof(ZoomNet.Models.WebinarSummary))]
	[JsonSerializable(typeof(ZoomNet.Models.WebinarTemplate))]
	[JsonSerializable(typeof(ZoomNet.Models.WebinarType))]
	[JsonSerializable(typeof(ZoomNet.Models.WhoCanShare))]
	[JsonSerializable(typeof(ZoomNet.Models.ZoomRoom))]
	[JsonSerializable(typeof(ZoomNet.Models.ZoomRoomIssueDetails))]
	[JsonSerializable(typeof(ZoomNet.Models.ZoomRoomWithIssues))]
	[JsonSerializable(typeof(ZoomNet.Models.ZoomRoomWithIssuesReport))]

	[JsonSerializable(typeof(ZoomNet.Models.Account[]))]
	[JsonSerializable(typeof(ZoomNet.Models.AccountCallLog[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ApprovalType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.Assistant[]))]
	[JsonSerializable(typeof(ZoomNet.Models.AttendeeChatSaveType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.AttendeeChatType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.AudioConferencingCallSettings[]))]
	[JsonSerializable(typeof(ZoomNet.Models.AudioConferencingPhoneNumberInformation[]))]
	[JsonSerializable(typeof(ZoomNet.Models.AudioConferencingUserSettings[]))]
	[JsonSerializable(typeof(ZoomNet.Models.AudioType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.AuthenticationOptions[]))]
	[JsonSerializable(typeof(ZoomNet.Models.AuthenticationSettings[]))]
	[JsonSerializable(typeof(ZoomNet.Models.AuthenticationType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.AutoRecordingType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.BatchRegistrant[]))]
	[JsonSerializable(typeof(ZoomNet.Models.BatchRegistrantInfo[]))]
	[JsonSerializable(typeof(ZoomNet.Models.BillingBasePlanUsage[]))]
	[JsonSerializable(typeof(ZoomNet.Models.BillingEmployeeCount[]))]
	[JsonSerializable(typeof(ZoomNet.Models.BillingInfo[]))]
	[JsonSerializable(typeof(ZoomNet.Models.BillingInvoiceDetails[]))]
	[JsonSerializable(typeof(ZoomNet.Models.BillingInvoiceItem[]))]
	[JsonSerializable(typeof(ZoomNet.Models.BillingInvoiceSummary[]))]
	[JsonSerializable(typeof(ZoomNet.Models.BillingPlanUsage[]))]
	[JsonSerializable(typeof(ZoomNet.Models.BillingPlanUsageInfo[]))]
	[JsonSerializable(typeof(ZoomNet.Models.BillingRecordingPlanUsage[]))]
	[JsonSerializable(typeof(ZoomNet.Models.BillingUnitedPlanUsage[]))]
	[JsonSerializable(typeof(ZoomNet.Models.CalendarIntegrationType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.CallHandlingSettings.BusyOnAnotherCallActionType[]), TypeInfoPropertyName = "CallHandlingSettingsBusyOnAnotherCallActionTypeArray")]
	[JsonSerializable(typeof(ZoomNet.Models.CallHandlingSettings.CallDistributionSettings[]), TypeInfoPropertyName = "CallHandlingSettingsCallDistributionSettingsArray")]
	[JsonSerializable(typeof(ZoomNet.Models.CallHandlingSettings.CallForwardingChildSubsettings[]), TypeInfoPropertyName = "CallHandlingSettingsCallForwardingChildSubsettingsArray")]
	[JsonSerializable(typeof(ZoomNet.Models.CallHandlingSettings.CallForwardingSubsettings[]), TypeInfoPropertyName = "CallHandlingSettingsCallForwardingSubsettingsArray")]
	[JsonSerializable(typeof(ZoomNet.Models.CallHandlingSettings.CallHandlingSettingType[]), TypeInfoPropertyName = "CallHandlingSettingsCallHandlingSettingTypeArray")]
	[JsonSerializable(typeof(ZoomNet.Models.CallHandlingSettings.CallHandlingSubsettings[]), TypeInfoPropertyName = "CallHandlingSettingsCallHandlingSubsettingsArray")]
	[JsonSerializable(typeof(ZoomNet.Models.CallHandlingSettings.CallHandlingSubsettingsBase[]), TypeInfoPropertyName = "CallHandlingSettingsCallHandlingSubsettingsBaseArray")]
	[JsonSerializable(typeof(ZoomNet.Models.CallHandlingSettings.CallHandlingSubsettingsType[]), TypeInfoPropertyName = "CallHandlingSettingsCallHandlingSubsettingsTypeArray")]
	[JsonSerializable(typeof(ZoomNet.Models.CallHandlingSettings.CallNotAnswerActionType[]), TypeInfoPropertyName = "CallHandlingSettingsCallNotAnswerActionTypeArray")]
	[JsonSerializable(typeof(ZoomNet.Models.CallHandlingSettings.CustomHoursChildSubsettings[]), TypeInfoPropertyName = "CallHandlingSettingsCustomHoursChildSubsettingsArray")]
	[JsonSerializable(typeof(ZoomNet.Models.CallHandlingSettings.CustomHoursSubsettings[]), TypeInfoPropertyName = "CallHandlingSettingsCustomHoursSubsettingsArray")]
	[JsonSerializable(typeof(ZoomNet.Models.CallHandlingSettings.CustomHoursType[]), TypeInfoPropertyName = "CallHandlingSettingsCustomHoursTypeArray")]
	[JsonSerializable(typeof(ZoomNet.Models.CallHandlingSettings.HolidaySubsettings[]), TypeInfoPropertyName = "CallHandlingSettingsHolidaySubsettingsArray")]
	[JsonSerializable(typeof(ZoomNet.Models.CallHandlingSettings.RingModeType[]), TypeInfoPropertyName = "CallHandlingSettingsRingModeTypeArray")]
	[JsonSerializable(typeof(ZoomNet.Models.CallingPlan[]))]
	[JsonSerializable(typeof(ZoomNet.Models.CallingPlanType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.CallLog[]))]
	[JsonSerializable(typeof(ZoomNet.Models.CallLogCalleeNumberType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.CallLogCallerNumberType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.CallLogCallType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.CallLogDirection[]))]
	[JsonSerializable(typeof(ZoomNet.Models.CallLogNumberSource[]))]
	[JsonSerializable(typeof(ZoomNet.Models.CallLogOwnerInfo[]))]
	[JsonSerializable(typeof(ZoomNet.Models.CallLogOwnerType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.CallLogPathType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.CallLogResult[]))]
	[JsonSerializable(typeof(ZoomNet.Models.CallLogSite[]))]
	[JsonSerializable(typeof(ZoomNet.Models.CallLogTimeType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.CallLogTransferInfo[]))]
	[JsonSerializable(typeof(ZoomNet.Models.CallLogTransferInfoExtensionType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.CallLogTransferInfoNumberType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.CallLogType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ChatbotMessage.ChatbotAction[]), TypeInfoPropertyName = "ChatbotMessageChatbotActionArray")]
	[JsonSerializable(typeof(ZoomNet.Models.ChatbotMessage.ChatbotActions[]), TypeInfoPropertyName = "ChatbotMessageChatbotActionsArray")]
	[JsonSerializable(typeof(ZoomNet.Models.ChatbotMessage.ChatbotActionStyle[]), TypeInfoPropertyName = "ChatbotMessageChatbotActionStyleArray")]
	[JsonSerializable(typeof(ZoomNet.Models.ChatbotMessage.ChatbotAttachment[]), TypeInfoPropertyName = "ChatbotMessageChatbotAttachmentArray")]
	[JsonSerializable(typeof(ZoomNet.Models.ChatbotMessage.ChatbotAttachmentInformation[]), TypeInfoPropertyName = "ChatbotMessageChatbotAttachmentInformationArray")]
	[JsonSerializable(typeof(ZoomNet.Models.ChatbotMessage.ChatbotContent[]), TypeInfoPropertyName = "ChatbotMessageChatbotContentArray")]
	[JsonSerializable(typeof(ZoomNet.Models.ChatbotMessage.ChatbotDropdownItem[]), TypeInfoPropertyName = "ChatbotMessageChatbotDropdownItemArray")]
	[JsonSerializable(typeof(ZoomNet.Models.ChatbotMessage.ChatbotDropdownList[]), TypeInfoPropertyName = "ChatbotMessageChatbotDropdownListArray")]
	[JsonSerializable(typeof(ZoomNet.Models.ChatbotMessage.ChatbotDropdownStaticSource[]), TypeInfoPropertyName = "ChatbotMessageChatbotDropdownStaticSourceArray")]
	[JsonSerializable(typeof(ZoomNet.Models.ChatbotMessage.ChatbotFormField[]), TypeInfoPropertyName = "ChatbotMessageChatbotFormFieldArray")]
	[JsonSerializable(typeof(ZoomNet.Models.ChatbotMessage.ChatbotFormFields[]), TypeInfoPropertyName = "ChatbotMessageChatbotFormFieldsArray")]
	[JsonSerializable(typeof(ZoomNet.Models.ChatbotMessage.ChatbotHeader[]), TypeInfoPropertyName = "ChatbotMessageChatbotHeaderArray")]
	[JsonSerializable(typeof(ZoomNet.Models.ChatbotMessage.ChatbotMessageLine[]), TypeInfoPropertyName = "ChatbotMessageChatbotMessageLineArray")]
	[JsonSerializable(typeof(ZoomNet.Models.ChatbotMessage.ChatbotMessageStyle[]), TypeInfoPropertyName = "ChatbotMessageChatbotMessageStyleArray")]
	[JsonSerializable(typeof(ZoomNet.Models.ChatbotMessage.ChatbotMessageText[]), TypeInfoPropertyName = "ChatbotMessageChatbotMessageTextArray")]
	[JsonSerializable(typeof(ZoomNet.Models.ChatbotMessage.ChatbotSection[]), TypeInfoPropertyName = "ChatbotMessageChatbotSectionArray")]
	[JsonSerializable(typeof(ZoomNet.Models.ChatbotMessageInformation[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ChatChannel[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ChatChannelAddMemberPermissions[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ChatChannelMember[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ChatChannelMentionAllPermissions[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ChatChannelPostingPermissions[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ChatChannelRole[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ChatChannelSettings[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ChatChannelType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ChatMembersEditResult[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ChatMention[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ChatMentionType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ChatMessage[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ChimeType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ClientFeedbackDetail[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ClientFeedbackMetrics[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ClientFeedbackMetricsReport[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ClientSatisfactionMetrics[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ClientSatisfactionReport[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ClosedCaptioningSettings[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ConcurrentMeetingType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.Contact[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ContactType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ContinuousMeetingChatSettings[]))]
	[JsonSerializable(typeof(ZoomNet.Models.Country[]))]
	[JsonSerializable(typeof(ZoomNet.Models.CrcPortMetrics[]))]
	[JsonSerializable(typeof(ZoomNet.Models.CrcPortsHourUsage[]))]
	[JsonSerializable(typeof(ZoomNet.Models.CrcPortsUsage[]))]
	[JsonSerializable(typeof(ZoomNet.Models.CustomAttribute[]))]
	[JsonSerializable(typeof(ZoomNet.Models.DailyUsageReport[]))]
	[JsonSerializable(typeof(ZoomNet.Models.DailyUsageSummary[]))]
	[JsonSerializable(typeof(ZoomNet.Models.DashboardMeetingMetrics[]))]
	[JsonSerializable(typeof(ZoomNet.Models.DashboardMeetingMetricsPaginationObject[]))]
	[JsonSerializable(typeof(ZoomNet.Models.DashboardMeetingParticipant[]))]
	[JsonSerializable(typeof(ZoomNet.Models.DashboardMeetingParticipantQos[]))]
	[JsonSerializable(typeof(ZoomNet.Models.DashboardMeetingType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.DashboardMetricsBase[]))]
	[JsonSerializable(typeof(ZoomNet.Models.DashboardParticipant[]))]
	[JsonSerializable(typeof(ZoomNet.Models.DashboardParticipantQos[]))]
	[JsonSerializable(typeof(ZoomNet.Models.DataCenterRegion[]))]
	[JsonSerializable(typeof(ZoomNet.Models.EmailNotificationUserSettings[]))]
	[JsonSerializable(typeof(ZoomNet.Models.EmergencyAddress[]))]
	[JsonSerializable(typeof(ZoomNet.Models.EncryptionType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ExternalContact[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ExternalContactDetails[]))]
	[JsonSerializable(typeof(ZoomNet.Models.FeatureUserSettings[]))]
	[JsonSerializable(typeof(ZoomNet.Models.Group[]))]
	[JsonSerializable(typeof(ZoomNet.Models.GroupAdministrator[]))]
	[JsonSerializable(typeof(ZoomNet.Models.GroupMember[]))]
	[JsonSerializable(typeof(ZoomNet.Models.GroupMemberType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ImMetric[]))]
	[JsonSerializable(typeof(ZoomNet.Models.InstantMeeting[]))]
	[JsonSerializable(typeof(ZoomNet.Models.InstantMeetingUserSettings[]))]
	[JsonSerializable(typeof(ZoomNet.Models.InterpretationLanguage[]))]
	[JsonSerializable(typeof(ZoomNet.Models.InviteLink[]))]
	[JsonSerializable(typeof(ZoomNet.Models.IpAddressAccessControlSettings[]))]
	[JsonSerializable(typeof(ZoomNet.Models.IssuesOfZoomRooms[]))]
	[JsonSerializable(typeof(ZoomNet.Models.IssuesOfZoomRoomsReport[]))]
	[JsonSerializable(typeof(ZoomNet.Models.IssueType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.JoinBeforeHostTime[]))]
	[JsonSerializable(typeof(ZoomNet.Models.Language[]))]
	[JsonSerializable(typeof(ZoomNet.Models.LanguageInterpretationSettings[]))]
	[JsonSerializable(typeof(ZoomNet.Models.LiveStreamingInfo[]))]
	[JsonSerializable(typeof(ZoomNet.Models.LiveStreamingSettings[]))]
	[JsonSerializable(typeof(ZoomNet.Models.LoginType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ManualCaptioningSettings[]))]
	[JsonSerializable(typeof(ZoomNet.Models.Meeting[]))]
	[JsonSerializable(typeof(ZoomNet.Models.MeetingFile[]))]
	[JsonSerializable(typeof(ZoomNet.Models.MeetingListType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.MeetingOccurrence[]))]
	[JsonSerializable(typeof(ZoomNet.Models.MeetingSettings[]))]
	[JsonSerializable(typeof(ZoomNet.Models.MeetingStatus[]))]
	[JsonSerializable(typeof(ZoomNet.Models.MeetingSummary[]))]
	[JsonSerializable(typeof(ZoomNet.Models.MeetingTemplate[]))]
	[JsonSerializable(typeof(ZoomNet.Models.MeetingTemplateType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.MeetingType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.NumberOfEmployees[]))]
	[JsonSerializable(typeof(ZoomNet.Models.OAuthGrantType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.Panelist[]))]
	[JsonSerializable(typeof(ZoomNet.Models.Participant[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ParticipantChatSaveType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ParticipantChatType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ParticipantDevice[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ParticipantNetwork[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ParticipantSharingDetails[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ParticipantStatus[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ParticipantsToPlaceInWaitingRoom[]))]
	[JsonSerializable(typeof(ZoomNet.Models.PasswordRequirements[]))]
	[JsonSerializable(typeof(ZoomNet.Models.PastInstance[]))]
	[JsonSerializable(typeof(ZoomNet.Models.PastMeeting[]))]
	[JsonSerializable(typeof(ZoomNet.Models.PayMode[]))]
	[JsonSerializable(typeof(ZoomNet.Models.PhoneCallPhoneNumber[]))]
	[JsonSerializable(typeof(ZoomNet.Models.PhoneCallRecording[]))]
	[JsonSerializable(typeof(ZoomNet.Models.PhoneCallRecordingCalleeNumberType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.PhoneCallRecordingCallerNumberType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.PhoneCallRecordingDisclaimerStatus[]))]
	[JsonSerializable(typeof(ZoomNet.Models.PhoneCallRecordingOwner[]))]
	[JsonSerializable(typeof(ZoomNet.Models.PhoneCallRecordingOwnerExtensionStatus[]))]
	[JsonSerializable(typeof(ZoomNet.Models.PhoneCallRecordingOwnerType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.PhoneCallRecordingTranscript[]))]
	[JsonSerializable(typeof(ZoomNet.Models.PhoneCallRecordingTranscriptTimelineFraction[]))]
	[JsonSerializable(typeof(ZoomNet.Models.PhoneCallRecordingTranscriptTimelineUser[]))]
	[JsonSerializable(typeof(ZoomNet.Models.PhoneCallRecordingType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.PhoneCallUser[]))]
	[JsonSerializable(typeof(ZoomNet.Models.PhoneCallUserProfile[]))]
	[JsonSerializable(typeof(ZoomNet.Models.PhoneCallUserStatus[]))]
	[JsonSerializable(typeof(ZoomNet.Models.PhoneNumber[]))]
	[JsonSerializable(typeof(ZoomNet.Models.PhoneType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.PhoneUser[]))]
	[JsonSerializable(typeof(ZoomNet.Models.PhoneDetail[]))]
	[JsonSerializable(typeof(ZoomNet.Models.PmiMeetingPasswordRequirementType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.Poll[]))]
	[JsonSerializable(typeof(ZoomNet.Models.PollAnswer[]))]
	[JsonSerializable(typeof(ZoomNet.Models.PollPrompt[]))]
	[JsonSerializable(typeof(ZoomNet.Models.PollQuestion[]))]
	[JsonSerializable(typeof(ZoomNet.Models.PollQuestionType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.PollResult[]))]
	[JsonSerializable(typeof(ZoomNet.Models.PollStatus[]))]
	[JsonSerializable(typeof(ZoomNet.Models.PollType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.PresenceStatus[]))]
	[JsonSerializable(typeof(ZoomNet.Models.PresenceStatusResponse[]))]
	[JsonSerializable(typeof(ZoomNet.Models.PronounDisplayType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.PurchasingTimeFrame[]))]
	[JsonSerializable(typeof(ZoomNet.Models.QualityOfService.CpuUsage[]), TypeInfoPropertyName = "QualityOfServiceCpuUsageArray")]
	[JsonSerializable(typeof(ZoomNet.Models.QualityOfService.PacketQualityOfServiceMetrics[]), TypeInfoPropertyName = "QualityOfServicePacketQualityOfServiceMetricsArray")]
	[JsonSerializable(typeof(ZoomNet.Models.QualityOfService.VideoQualityOfServiceMetrics[]), TypeInfoPropertyName = "QualityOfServiceVideoQualityOfServiceMetricsArray")]
	[JsonSerializable(typeof(ZoomNet.Models.QualityType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.Recording[]))]
	[JsonSerializable(typeof(ZoomNet.Models.RecordingContentType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.RecordingFile[]))]
	[JsonSerializable(typeof(ZoomNet.Models.RecordingFileExtension[]))]
	[JsonSerializable(typeof(ZoomNet.Models.RecordingFileType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.RecordingRegistration[]))]
	[JsonSerializable(typeof(ZoomNet.Models.RecordingSettings[]))]
	[JsonSerializable(typeof(ZoomNet.Models.RecordingSharingType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.RecordingStatus[]))]
	[JsonSerializable(typeof(ZoomNet.Models.RecordingType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.RecordingUserSettings[]))]
	[JsonSerializable(typeof(ZoomNet.Models.RecurrenceInfo[]))]
	[JsonSerializable(typeof(ZoomNet.Models.RecurrenceType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.RecurringMeeting[]))]
	[JsonSerializable(typeof(ZoomNet.Models.RecurringWebinar[]))]
	[JsonSerializable(typeof(ZoomNet.Models.Registrant[]))]
	[JsonSerializable(typeof(ZoomNet.Models.RegistrantInfo[]))]
	[JsonSerializable(typeof(ZoomNet.Models.RegistrantStatus[]))]
	[JsonSerializable(typeof(ZoomNet.Models.RegistrationAnswer[]))]
	[JsonSerializable(typeof(ZoomNet.Models.RegistrationCustomQuestionForMeeting[]))]
	[JsonSerializable(typeof(ZoomNet.Models.RegistrationCustomQuestionForWebinar[]))]
	[JsonSerializable(typeof(ZoomNet.Models.RegistrationCustomQuestionTypeForMeeting[]))]
	[JsonSerializable(typeof(ZoomNet.Models.RegistrationCustomQuestionTypeForWebinar[]))]
	[JsonSerializable(typeof(ZoomNet.Models.RegistrationField[]))]
	[JsonSerializable(typeof(ZoomNet.Models.RegistrationQuestionsForMeeting[]))]
	[JsonSerializable(typeof(ZoomNet.Models.RegistrationQuestionsForWebinar[]))]
	[JsonSerializable(typeof(ZoomNet.Models.RegistrationType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ReportHost[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ReportHostType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ReportMeetingType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ReportParticipant[]))]
	[JsonSerializable(typeof(ZoomNet.Models.Role[]))]
	[JsonSerializable(typeof(ZoomNet.Models.RoleInPurchaseProcess[]))]
	[JsonSerializable(typeof(ZoomNet.Models.Room[]))]
	[JsonSerializable(typeof(ZoomNet.Models.RoomLocation[]))]
	[JsonSerializable(typeof(ZoomNet.Models.RoomLocationAlertSettings[]))]
	[JsonSerializable(typeof(ZoomNet.Models.RoomLocationBackgroundImageInfo[]))]
	[JsonSerializable(typeof(ZoomNet.Models.RoomLocationBasicProfile[]))]
	[JsonSerializable(typeof(ZoomNet.Models.RoomLocationIncomingMeetingRequestSettings[]))]
	[JsonSerializable(typeof(ZoomNet.Models.RoomLocationNotificationSettings[]))]
	[JsonSerializable(typeof(ZoomNet.Models.RoomLocationReserveOtherRoomsSettings[]))]
	[JsonSerializable(typeof(ZoomNet.Models.RoomLocationSchedulingDisplaySettings[]))]
	[JsonSerializable(typeof(ZoomNet.Models.RoomLocationSecuritySettings[]))]
	[JsonSerializable(typeof(ZoomNet.Models.RoomLocationSettings[]))]
	[JsonSerializable(typeof(ZoomNet.Models.RoomLocationSettingsType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.RoomLocationSetupProfile[]))]
	[JsonSerializable(typeof(ZoomNet.Models.RoomLocationSignageSettings[]))]
	[JsonSerializable(typeof(ZoomNet.Models.RoomLocationType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.RoomTag[]))]
	[JsonSerializable(typeof(ZoomNet.Models.RoomType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ScheduledMeeting[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ScheduledMeetingUserSettings[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ScheduledWebinar[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ScreenshareContentType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ScreenshareDetails[]))]
	[JsonSerializable(typeof(ZoomNet.Models.SecuritySettings[]))]
	[JsonSerializable(typeof(ZoomNet.Models.SharingAndRecordingDetail[]))]
	[JsonSerializable(typeof(ZoomNet.Models.SignageBannerDisplayPeriod[]))]
	[JsonSerializable(typeof(ZoomNet.Models.SignageBannerSettings[]))]
	[JsonSerializable(typeof(ZoomNet.Models.SignageContentItem[]))]
	[JsonSerializable(typeof(ZoomNet.Models.SignageContentList[]))]
	[JsonSerializable(typeof(ZoomNet.Models.SignageLayout[]))]
	[JsonSerializable(typeof(ZoomNet.Models.Site[]))]
	[JsonSerializable(typeof(ZoomNet.Models.SmsAttachment[]))]
	[JsonSerializable(typeof(ZoomNet.Models.SmsAttachmentType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.SmsDirection[]))]
	[JsonSerializable(typeof(ZoomNet.Models.SmsHistoryParticipant[]))]
	[JsonSerializable(typeof(ZoomNet.Models.SmsMessage[]))]
	[JsonSerializable(typeof(ZoomNet.Models.SmsMessageType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.SmsParticipantOwner[]))]
	[JsonSerializable(typeof(ZoomNet.Models.SmsParticipantOwnerType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.StreamingService[]))]
	[JsonSerializable(typeof(ZoomNet.Models.Survey[]))]
	[JsonSerializable(typeof(ZoomNet.Models.SurveyDetails[]))]
	[JsonSerializable(typeof(ZoomNet.Models.SurveyQuestion[]))]
	[JsonSerializable(typeof(ZoomNet.Models.SurveyQuestionType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.TelephonyRegionsSettings[]))]
	[JsonSerializable(typeof(ZoomNet.Models.TelephonyUserSettings[]))]
	[JsonSerializable(typeof(ZoomNet.Models.TimeZones[]))]
	[JsonSerializable(typeof(ZoomNet.Models.TrackingField[]))]
	[JsonSerializable(typeof(ZoomNet.Models.TrackingSource[]))]
	[JsonSerializable(typeof(ZoomNet.Models.TspUserSettings[]))]
	[JsonSerializable(typeof(ZoomNet.Models.User[]))]
	[JsonSerializable(typeof(ZoomNet.Models.UserCallLog[]))]
	[JsonSerializable(typeof(ZoomNet.Models.UserCreateType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.UserProfile[]))]
	[JsonSerializable(typeof(ZoomNet.Models.UserRecordingStorageSettings[]))]
	[JsonSerializable(typeof(ZoomNet.Models.UserSettings[]))]
	[JsonSerializable(typeof(ZoomNet.Models.UserStatus[]))]
	[JsonSerializable(typeof(ZoomNet.Models.UsersWhoCanAdmitParticipantsFromWaitingRoom[]))]
	[JsonSerializable(typeof(ZoomNet.Models.UserType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.VirtualBackgroundFile[]))]
	[JsonSerializable(typeof(ZoomNet.Models.VirtualBackgroundSettings[]))]
	[JsonSerializable(typeof(ZoomNet.Models.VirtualBackgroundType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.WaitingRoomSettings[]))]
	[JsonSerializable(typeof(ZoomNet.Models.WebhookParticipant[]))]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.AppDeauthorizedEvent[]), TypeInfoPropertyName = "WebhooksAppDeauthorizedEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.EndpointUrlValidationEvent[]), TypeInfoPropertyName = "WebhooksEndpointUrlValidationEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.Event[]), TypeInfoPropertyName = "WebhooksEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.EventType[]), TypeInfoPropertyName = "WebhooksEventTypeArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingCreatedEvent[]), TypeInfoPropertyName = "WebhooksMeetingCreatedEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingDeletedEvent[]), TypeInfoPropertyName = "WebhooksMeetingDeletedEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingEndedEvent[]), TypeInfoPropertyName = "WebhooksMeetingEndedEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingEvent[]), TypeInfoPropertyName = "WebhooksMeetingEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingLiveStreamStartedEvent[]), TypeInfoPropertyName = "WebhooksMeetingLiveStreamStartedEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingLiveStreamStoppedEvent[]), TypeInfoPropertyName = "WebhooksMeetingLiveStreamStoppedEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingParticipantAdmittedEvent[]), TypeInfoPropertyName = "WebhooksMeetingParticipantAdmittedEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingParticipantJoinedBeforeHostEvent[]), TypeInfoPropertyName = "WebhooksMeetingParticipantJoinedBeforeHostEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingParticipantJoinedEvent[]), TypeInfoPropertyName = "WebhooksMeetingParticipantJoinedEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingParticipantJoinedWaitingRoomEvent[]), TypeInfoPropertyName = "WebhooksMeetingParticipantJoinedWaitingRoomEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingParticipantLeftEvent[]), TypeInfoPropertyName = "WebhooksMeetingParticipantLeftEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingParticipantLeftWaitingRoomEvent[]), TypeInfoPropertyName = "WebhooksMeetingParticipantLeftWaitingRoomEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingParticipantSentToWaitingRoomEvent[]), TypeInfoPropertyName = "WebhooksMeetingParticipantSentToWaitingRoomEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingParticipantWaitingForHostEvent[]), TypeInfoPropertyName = "WebhooksMeetingParticipantWaitingForHostEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingPermanentlyDeletedEvent[]), TypeInfoPropertyName = "WebhooksMeetingPermanentlyDeletedEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingRecoveredEvent[]), TypeInfoPropertyName = "WebhooksMeetingRecoveredEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingRegistrationApprovedEvent[]), TypeInfoPropertyName = "WebhooksMeetingRegistrationApprovedEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingRegistrationCancelledEvent[]), TypeInfoPropertyName = "WebhooksMeetingRegistrationCancelledEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingRegistrationCreatedEvent[]), TypeInfoPropertyName = "WebhooksMeetingRegistrationCreatedEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingRegistrationDeniedEvent[]), TypeInfoPropertyName = "WebhooksMeetingRegistrationDeniedEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingServiceIssueEvent[]), TypeInfoPropertyName = "WebhooksMeetingServiceIssueEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingSharingEndedEvent[]), TypeInfoPropertyName = "WebhooksMeetingSharingEndedEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingSharingStartedEvent[]), TypeInfoPropertyName = "WebhooksMeetingSharingStartedEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingStartedEvent[]), TypeInfoPropertyName = "WebhooksMeetingStartedEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.MeetingUpdatedEvent[]), TypeInfoPropertyName = "WebhooksMeetingUpdatedEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.RecordingCompletedEvent[]), TypeInfoPropertyName = "WebhooksRecordingCompletedEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.RecordingEvent[]), TypeInfoPropertyName = "WebhooksRecordingEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.WebinarCreatedEvent[]), TypeInfoPropertyName = "WebhooksWebinarCreatedEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.WebinarDeletedEvent[]), TypeInfoPropertyName = "WebhooksWebinarDeletedEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.WebinarEndedEvent[]), TypeInfoPropertyName = "WebhooksWebinarEndedEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.WebinarEvent[]), TypeInfoPropertyName = "WebhooksWebinarEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.WebinarParticipantJoinedEvent[]), TypeInfoPropertyName = "WebhooksWebinarParticipantJoinedEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.WebinarParticipantLeftEvent[]), TypeInfoPropertyName = "WebhooksWebinarParticipantLeftEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.WebinarRegistrationApprovedEvent[]), TypeInfoPropertyName = "WebhooksWebinarRegistrationApprovedEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.WebinarRegistrationCancelledEvent[]), TypeInfoPropertyName = "WebhooksWebinarRegistrationCancelledEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.WebinarRegistrationCreatedEvent[]), TypeInfoPropertyName = "WebhooksWebinarRegistrationCreatedEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.WebinarRegistrationDeniedEvent[]), TypeInfoPropertyName = "WebhooksWebinarRegistrationDeniedEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.WebinarServiceIssueEvent[]), TypeInfoPropertyName = "WebhooksWebinarServiceIssueEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.WebinarSharingEndedEvent[]), TypeInfoPropertyName = "WebhooksWebinarSharingEndedEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.WebinarSharingStartedEvent[]), TypeInfoPropertyName = "WebhooksWebinarSharingStartedEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.WebinarStartedEvent[]), TypeInfoPropertyName = "WebhooksWebinarStartedEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.WebinarUpdatedEvent[]), TypeInfoPropertyName = "WebhooksWebinarUpdatedEventArray")]
	[JsonSerializable(typeof(ZoomNet.Models.Webinar[]))]
	[JsonSerializable(typeof(ZoomNet.Models.WebinarChatSettings[]))]
	[JsonSerializable(typeof(ZoomNet.Models.WebinarChatType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.WebinarLiveStreamingSettings[]))]
	[JsonSerializable(typeof(ZoomNet.Models.WebinarPollingSettings[]))]
	[JsonSerializable(typeof(ZoomNet.Models.WebinarSettings[]))]
	[JsonSerializable(typeof(ZoomNet.Models.WebinarSummary[]))]
	[JsonSerializable(typeof(ZoomNet.Models.WebinarTemplate[]))]
	[JsonSerializable(typeof(ZoomNet.Models.WebinarType[]))]
	[JsonSerializable(typeof(ZoomNet.Models.WhoCanShare[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ZoomRoom[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ZoomRoomIssueDetails[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ZoomRoomWithIssues[]))]
	[JsonSerializable(typeof(ZoomNet.Models.ZoomRoomWithIssuesReport[]))]

	[JsonSerializable(typeof(ZoomNet.Models.ApprovalType?))]
	[JsonSerializable(typeof(ZoomNet.Models.AttendeeChatSaveType?))]
	[JsonSerializable(typeof(ZoomNet.Models.AttendeeChatType?))]
	[JsonSerializable(typeof(ZoomNet.Models.AudioType?))]
	[JsonSerializable(typeof(ZoomNet.Models.AuthenticationType?))]
	[JsonSerializable(typeof(ZoomNet.Models.AutoRecordingType?))]
	[JsonSerializable(typeof(ZoomNet.Models.BillingEmployeeCount?))]
	[JsonSerializable(typeof(ZoomNet.Models.CalendarIntegrationType?))]
	[JsonSerializable(typeof(ZoomNet.Models.CallHandlingSettings.BusyOnAnotherCallActionType?), TypeInfoPropertyName = "CallHandlingSettingsBusyOnAnotherCallActionTypeNullable")]
	[JsonSerializable(typeof(ZoomNet.Models.CallHandlingSettings.CallHandlingSettingType?), TypeInfoPropertyName = "CallHandlingSettingsCallHandlingSettingTypeNullable")]
	[JsonSerializable(typeof(ZoomNet.Models.CallHandlingSettings.CallHandlingSubsettingsType?), TypeInfoPropertyName = "CallHandlingSettingsCallHandlingSubsettingsTypeNullable")]
	[JsonSerializable(typeof(ZoomNet.Models.CallHandlingSettings.CallNotAnswerActionType?), TypeInfoPropertyName = "CallHandlingSettingsCallNotAnswerActionTypeNullable")]
	[JsonSerializable(typeof(ZoomNet.Models.CallHandlingSettings.CustomHoursType?), TypeInfoPropertyName = "CallHandlingSettingsCustomHoursTypeNullable")]
	[JsonSerializable(typeof(ZoomNet.Models.CallHandlingSettings.RingModeType?), TypeInfoPropertyName = "CallHandlingSettingsRingModeTypeNullable")]
	[JsonSerializable(typeof(ZoomNet.Models.CallingPlanType?))]
	[JsonSerializable(typeof(ZoomNet.Models.CallLogCalleeNumberType?))]
	[JsonSerializable(typeof(ZoomNet.Models.CallLogCallerNumberType?))]
	[JsonSerializable(typeof(ZoomNet.Models.CallLogCallType?))]
	[JsonSerializable(typeof(ZoomNet.Models.CallLogDirection?))]
	[JsonSerializable(typeof(ZoomNet.Models.CallLogNumberSource?))]
	[JsonSerializable(typeof(ZoomNet.Models.CallLogOwnerType?))]
	[JsonSerializable(typeof(ZoomNet.Models.CallLogPathType?))]
	[JsonSerializable(typeof(ZoomNet.Models.CallLogResult?))]
	[JsonSerializable(typeof(ZoomNet.Models.CallLogTimeType?))]
	[JsonSerializable(typeof(ZoomNet.Models.CallLogTransferInfoExtensionType?))]
	[JsonSerializable(typeof(ZoomNet.Models.CallLogTransferInfoNumberType?))]
	[JsonSerializable(typeof(ZoomNet.Models.CallLogType?))]
	[JsonSerializable(typeof(ZoomNet.Models.ChatbotMessage.ChatbotActionStyle?), TypeInfoPropertyName = "ChatbotMessageChatbotActionStyleNullable")]
	[JsonSerializable(typeof(ZoomNet.Models.ChatbotMessage.ChatbotDropdownStaticSource?), TypeInfoPropertyName = "ChatbotMessageChatbotDropdownStaticSourceNullable")]
	[JsonSerializable(typeof(ZoomNet.Models.ChatChannelAddMemberPermissions?))]
	[JsonSerializable(typeof(ZoomNet.Models.ChatChannelMentionAllPermissions?))]
	[JsonSerializable(typeof(ZoomNet.Models.ChatChannelPostingPermissions?))]
	[JsonSerializable(typeof(ZoomNet.Models.ChatChannelRole?))]
	[JsonSerializable(typeof(ZoomNet.Models.ChatChannelType?))]
	[JsonSerializable(typeof(ZoomNet.Models.ChatMentionType?))]
	[JsonSerializable(typeof(ZoomNet.Models.ChimeType?))]
	[JsonSerializable(typeof(ZoomNet.Models.ConcurrentMeetingType?))]
	[JsonSerializable(typeof(ZoomNet.Models.ContactType?))]
	[JsonSerializable(typeof(ZoomNet.Models.Country?))]
	[JsonSerializable(typeof(ZoomNet.Models.DashboardMeetingType?))]
	[JsonSerializable(typeof(ZoomNet.Models.DataCenterRegion?))]
	[JsonSerializable(typeof(ZoomNet.Models.EncryptionType?))]
	[JsonSerializable(typeof(ZoomNet.Models.GroupMemberType?))]
	[JsonSerializable(typeof(ZoomNet.Models.InterpretationLanguage?))]
	[JsonSerializable(typeof(ZoomNet.Models.IssueType?))]
	[JsonSerializable(typeof(ZoomNet.Models.JoinBeforeHostTime?))]
	[JsonSerializable(typeof(ZoomNet.Models.Language?))]
	[JsonSerializable(typeof(ZoomNet.Models.LoginType?))]
	[JsonSerializable(typeof(ZoomNet.Models.MeetingListType?))]
	[JsonSerializable(typeof(ZoomNet.Models.MeetingStatus?))]
	[JsonSerializable(typeof(ZoomNet.Models.MeetingTemplateType?))]
	[JsonSerializable(typeof(ZoomNet.Models.MeetingType?))]
	[JsonSerializable(typeof(ZoomNet.Models.NumberOfEmployees?))]
	[JsonSerializable(typeof(ZoomNet.Models.OAuthGrantType?))]
	[JsonSerializable(typeof(ZoomNet.Models.ParticipantChatSaveType?))]
	[JsonSerializable(typeof(ZoomNet.Models.ParticipantChatType?))]
	[JsonSerializable(typeof(ZoomNet.Models.ParticipantDevice?))]
	[JsonSerializable(typeof(ZoomNet.Models.ParticipantNetwork?))]
	[JsonSerializable(typeof(ZoomNet.Models.ParticipantStatus?))]
	[JsonSerializable(typeof(ZoomNet.Models.ParticipantsToPlaceInWaitingRoom?))]
	[JsonSerializable(typeof(ZoomNet.Models.PayMode?))]
	[JsonSerializable(typeof(ZoomNet.Models.PhoneCallRecordingCalleeNumberType?))]
	[JsonSerializable(typeof(ZoomNet.Models.PhoneCallRecordingCallerNumberType?))]
	[JsonSerializable(typeof(ZoomNet.Models.PhoneCallRecordingDisclaimerStatus?))]
	[JsonSerializable(typeof(ZoomNet.Models.PhoneCallRecordingOwnerExtensionStatus?))]
	[JsonSerializable(typeof(ZoomNet.Models.PhoneCallRecordingOwnerType?))]
	[JsonSerializable(typeof(ZoomNet.Models.PhoneCallRecordingType?))]
	[JsonSerializable(typeof(ZoomNet.Models.PhoneCallUserStatus?))]
	[JsonSerializable(typeof(ZoomNet.Models.PhoneType?))]
	[JsonSerializable(typeof(ZoomNet.Models.PmiMeetingPasswordRequirementType?))]
	[JsonSerializable(typeof(ZoomNet.Models.PollQuestionType?))]
	[JsonSerializable(typeof(ZoomNet.Models.PollStatus?))]
	[JsonSerializable(typeof(ZoomNet.Models.PollType?))]
	[JsonSerializable(typeof(ZoomNet.Models.PresenceStatus?))]
	[JsonSerializable(typeof(ZoomNet.Models.PronounDisplayType?))]
	[JsonSerializable(typeof(ZoomNet.Models.PurchasingTimeFrame?))]
	[JsonSerializable(typeof(ZoomNet.Models.QualityType?))]
	[JsonSerializable(typeof(ZoomNet.Models.RecordingContentType?))]
	[JsonSerializable(typeof(ZoomNet.Models.RecordingFileExtension?))]
	[JsonSerializable(typeof(ZoomNet.Models.RecordingFileType?))]
	[JsonSerializable(typeof(ZoomNet.Models.RecordingSharingType?))]
	[JsonSerializable(typeof(ZoomNet.Models.RecordingStatus?))]
	[JsonSerializable(typeof(ZoomNet.Models.RecordingType?))]
	[JsonSerializable(typeof(ZoomNet.Models.RecurrenceType?))]
	[JsonSerializable(typeof(ZoomNet.Models.RegistrantStatus?))]
	[JsonSerializable(typeof(ZoomNet.Models.RegistrationCustomQuestionTypeForMeeting?))]
	[JsonSerializable(typeof(ZoomNet.Models.RegistrationCustomQuestionTypeForWebinar?))]
	[JsonSerializable(typeof(ZoomNet.Models.RegistrationField?))]
	[JsonSerializable(typeof(ZoomNet.Models.RegistrationType?))]
	[JsonSerializable(typeof(ZoomNet.Models.ReportHostType?))]
	[JsonSerializable(typeof(ZoomNet.Models.ReportMeetingType?))]
	[JsonSerializable(typeof(ZoomNet.Models.RoleInPurchaseProcess?))]
	[JsonSerializable(typeof(ZoomNet.Models.RoomLocationSettingsType?))]
	[JsonSerializable(typeof(ZoomNet.Models.RoomLocationType?))]
	[JsonSerializable(typeof(ZoomNet.Models.RoomType?))]
	[JsonSerializable(typeof(ZoomNet.Models.ScreenshareContentType?))]
	[JsonSerializable(typeof(ZoomNet.Models.SignageLayout?))]
	[JsonSerializable(typeof(ZoomNet.Models.SmsAttachmentType?))]
	[JsonSerializable(typeof(ZoomNet.Models.SmsDirection?))]
	[JsonSerializable(typeof(ZoomNet.Models.SmsMessageType?))]
	[JsonSerializable(typeof(ZoomNet.Models.SmsParticipantOwnerType?))]
	[JsonSerializable(typeof(ZoomNet.Models.StreamingService?))]
	[JsonSerializable(typeof(ZoomNet.Models.SurveyQuestionType?))]
	[JsonSerializable(typeof(ZoomNet.Models.TimeZones?))]
	[JsonSerializable(typeof(ZoomNet.Models.UserCreateType?))]
	[JsonSerializable(typeof(ZoomNet.Models.UserStatus?))]
	[JsonSerializable(typeof(ZoomNet.Models.UsersWhoCanAdmitParticipantsFromWaitingRoom?))]
	[JsonSerializable(typeof(ZoomNet.Models.UserType?))]
	[JsonSerializable(typeof(ZoomNet.Models.VirtualBackgroundType?))]
	[JsonSerializable(typeof(ZoomNet.Models.Webhooks.EventType?), TypeInfoPropertyName = "WebhooksEventTypeNullable")]
	[JsonSerializable(typeof(ZoomNet.Models.WebinarChatType?))]
	[JsonSerializable(typeof(ZoomNet.Models.WebinarType?))]
	[JsonSerializable(typeof(ZoomNet.Models.WhoCanShare?))]
	internal partial class ZoomNetJsonSerializerContext : JsonSerializerContext
	{
	}
}
